import { useQuery } from '@tanstack/react-query';
import { createContext, useContext, useMemo, type ReactNode } from 'react';

import { useAppRuntime } from '../app/providers.js';
import { principalPreferencesQueryKey } from '../app/query-keys.js';

export type ProductLocale = 'ko-KR' | 'en-US';

const enUS = {
  'common.close': 'Close',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.saving': 'Saving...',
  'common.checking': 'Checking...',
  'common.check_result': 'Check result',
  'common.loading_preferences': 'Loading preferences...',
  'shell.current_project': 'Current project',
  'shell.not_created': 'Not created',
  'shell.primary_navigation': 'Primary navigation',
  'shell.mobile_navigation': 'Mobile navigation',
  'shell.offline':
    'Offline. Cached information may be stale; server actions and Search are disabled.',
  'shell.additional_states': 'additional states',
  'nav.home': 'Home',
  'nav.sources': 'Sources',
  'nav.ask': 'Ask',
  'nav.available': 'Available',
  'nav.coming_later': 'Coming later',
  'nav.temporarily_unavailable': 'Temporarily unavailable',
  'nav.access_restricted': 'Access restricted',
  'home.first_run': 'First run',
  'home.create_first_project': 'Create your first Project',
  'home.create_first_project_help': 'Create your first Project to get started.',
  'home.open_onboarding': 'Open Project onboarding',
  'home.action_center': 'Action Center',
  'home.primary_actions': 'Primary Actions',
  'home.attention': 'Attention',
  'home.continue_working': 'Continue Working',
  'home.recent_and_pinned': 'Recent and Pinned',
  'commands.title': 'Commands',
  'commands.help': 'Find a command by name, alias, or keyword.',
  'commands.search_label': 'Command search',
  'commands.no_match': 'No matching commands.',
  'commands.category.help': 'Help',
  'commands.category.search': 'Search',
  'commands.category.project': 'Project',
  'commands.category.answer': 'Answer',
  'commands.category.ai': 'AI',
  'commands.category.privacy': 'Privacy',
  'commands.category.preferences': 'Preferences',
  'commands.category.navigation': 'Navigation',
  'commands.category.inspection': 'Inspection',
  'preferences.locale_title': 'Locale Preferences',
  'preferences.timezone_title': 'Timezone Preferences',
  'preferences.display_title': 'Display Preferences',
  'preferences.locale': 'Locale',
  'technical.title': 'Technical information',
  'privacy.review_title': 'Review Privacy',
  'privacy.project_title': 'Project Privacy',
  'privacy.loading': 'Loading privacy settings...',
  'privacy.open_review': 'Open privacy review',
  'privacy.request_review': 'Request external AI transfer review',
  'privacy.approve_review': 'Approve reviewed privacy proposal',
  'ai.configure': 'Configure AI',
  'ai.test': 'Test AI Connection',
  'ai.loading': 'Loading AI settings...',
  'ai.provider': 'Provider',
  'ai.model': 'Model',
  'ai.api_key': 'API Key (write-only)',
  'ai.test_connection': 'Test Connection',
  'ai.testing': 'Testing...',
  'ai.save_configuration': 'Save AI configuration',
  'ai.provider_privacy': 'Provider privacy',
  'ai.credential_actions': 'Credential actions',
  'project.manage': 'Manage Projects',
  'project.create': 'Create Project',
  'project.rename': 'Rename Project',
  'project.restore': 'Restore Project',
  'project.archive': 'Archive Project',
  'project.delete_request': 'Request Project Deletion',
  'project.loading': 'Loading Projects…',
  'project.active': 'Active Project',
  'project.rename_action': 'Rename',
  'project.archive_action': 'Archive',
  'project.restore_action': 'Restore',
  'project.request_deletion': 'Request deletion',
  'project.creating': 'Creating…',
  'project.restoring': 'Restoring…',
  'project.submitting': 'Submitting…',
  'project.confirm_archive': 'Confirm Archive',
  'project.confirm_deletion': 'Confirm Deletion Request',
  'search.title': 'Search',
  'search.query': 'Search query',
  'search.scope': 'Search scope',
  'search.active_project': 'Active Project',
  'search.selected_projects': 'Selected Projects',
  'search.submit': 'Search',
  'search.searching': 'Searching...',
  'search.loading': 'Searching the selected Project scope...',
  'search.no_results': 'No results in the selected Project scope.',
  'search.active_results': 'Results from the active Project.',
  'search.cross_results': 'Results from the selected accessible Projects.',
  'search.results_label': 'Search results',
  'ask.eyebrow': 'Knowledge question',
  'ask.title': 'Ask',
  'ask.question_draft': 'Question Draft',
  'ask.draft_help': 'Your question stays here until you submit it.',
  'ask.question': 'Question',
  'ask.submit': 'Submit question',
  'ask.submitting': 'Submitting...',
  'ask.conversations': 'Conversations',
  'ask.no_conversations': 'No conversations yet.',
  'ask.answer': 'Answer',
  'ask.answer_actions': 'Answer actions',
  'ask.selected_conversation': 'Selected conversation',
  'ask.partial_answer': 'Partial answer',
  'ask.open_evidence': 'Open pinned Evidence',
  'ask.answer_status': 'Answer status',
  'ask.cancel_answer': 'Cancel answer',
  'ask.answer_export': 'Answer export',
  'ask.create_or_select_project': 'Create or select a Project before asking questions.',
  'ask.loading_workspace': 'Loading Ask workspace…',
  'ask.mode': 'Ask mode',
  'ask.source_context': 'Source context',
  'ask.source_selection_unavailable': 'Source selection is unavailable for this question context.',
  'ask.loading_sources': 'Loading Sources…',
  'ask.sources_load_failed': 'Sources could not be loaded.',
  'ask.source_project_mismatch': 'The Source Library Project does not match this Ask resource.',
  'ask.no_sources': 'No Sources are available for Ask in this Project.',
  'ask.pinned_version': 'Pinned version',
  'ask.version': 'Version',
  'ask.check_submission_outcome': 'Check submission outcome',
  'ask.source_selection_required': 'Select at least one Source before using selected sources.',
  'ask.action_required': 'Action required:',
  'ask.review_privacy': 'Review privacy',
  'ask.provider_eligibility_unavailable':
    'Provider eligibility could not be verified. Submission remains unavailable.',
  'ask.submission_unavailable': 'Question submission is not available for this conversation.',
  'ask.current_conversation': '(current conversation)',
  'ask.conversation_list': 'Conversations',
  'ask.submission_rejected': 'The question submission was rejected. The Draft was preserved.',
  'ask.submission_outcome_unknown':
    'The submission outcome is still unknown. The original request identity and Draft are preserved.',
  'ask.checking_submission_outcome': 'Checking the existing submission outcome…',
  'ask.answer_result_unknown': 'The answer result is unknown. Check again before retrying.',
  'ask.answer_result_still_unknown':
    'The answer result is still unknown. Check again without submitting a new request.',
  'ask.request_rejected': 'The request was rejected. No new request was sent.',
  'ask.request_pending':
    'The request was accepted but is not resolved. No automatic retry was started.',
  'ask.result_unavailable':
    'The request completed, but its result is not available yet. Check again without submitting a new request.',
  'ask.answer_request_recovered': 'The completed answer request and its result were recovered.',
  'ask.answer_cancel_requested': 'Answer cancellation requested.',
  'ask.answer_retry_accepted': 'Answer retry accepted with a new attempt.',
  'ask.answer_export_completed': 'Answer export completed.',
  'ask.transition_proposed': 'A draft transition was proposed. Verified knowledge was not changed.',
  'ask.source_id': 'Source ID',
  'ask.source_version_id': 'SourceVersion ID',
  'ask.failure_code': 'Failure code',
  'answer.export': 'Export answer',
  'answer.retry': 'Retry answer',
  'answer.applies_selected': 'This action applies to the selected answer.',
  'answer.retry_same': 'Retry same context',
  'answer.retry_policy': 'Retry current policy',
  'answer.propose_intake': 'Propose Intake Draft',
  'answer.propose_change': 'Propose Draft ChangeSet',
  'answer.propose_directive': 'Propose Directive',
  'sources.title': 'Sources',
  'sources.eyebrow': 'Knowledge input',
  'sources.create_project': 'Create a Project before adding Sources',
  'sources.create_project_help': 'Create a Project to organize and add Sources.',
  'sources.draft_queue': 'Draft Queue',
  'sources.draft_help':
    'Drafts stay with the project where they were created until submitted or discarded.',
  'sources.no_drafts': 'No drafts yet.',
  'sources.library': 'Source Library',
  'sources.search': 'Search Sources',
  'sources.search_submit': 'Search',
  'sources.loading_library': 'Loading Source Library…',
  'sources.no_matching': 'No matching Sources',
  'sources.none_yet': 'No Sources yet',
  'sources.change_search': 'Change the Server search query or clear it.',
  'sources.submitted_appear': 'Submitted Sources will appear here after Server processing.',
  'sources.open': 'Open source',
  'sources.unavailable': 'This source is unavailable.',
  'sources.needs_attention': 'This source needs attention before it can be used.',
  'sources.question_access_restricted': 'Question access is restricted.',
  'sources.questions_not_ready': 'Not yet available for questions.',
  'sources.preview_unavailable': 'Preview is unavailable.',
  'sources.choose_file_again': 'Choose the file again before submission.',
  'sources.submission_failed': 'Sources submission failed.',
  'sources.duplicate_decision_failed': 'Duplicate decision failed.',
  'sources.duplicate_resolution_failed': 'Duplicate resolution failed.',
  'sources.cancellation_failed': 'Cancellation failed.',
  'sources.retry_failed': 'Retry failed.',
  'sources.project_mismatch':
    'The active Project changed. These drafts remain isolated to their original Project and cannot be submitted from the current context.',
  'sources.invalid_draft': 'This draft could not be opened. Review it and try again.',
  'sources.draft_message.seeded_text_review':
    'Seeded Direct Text must be reviewed before submission.',
  'sources.draft_message.seeded_text_too_large':
    'Seeded Direct Text exceeds the active one MiB boundary.',
  'sources.draft_message.seeded_url_validation':
    'The Server will repeat URL safety validation on submission.',
  'sources.draft_message.seed_file_reselect':
    'Choose the file again. A seed cannot supply browser file bytes.',
  'sources.draft_message.direct_text_empty': 'Direct Text cannot be empty.',
  'sources.draft_message.direct_text_too_large': 'Direct Text exceeds the active one MiB limit.',
  'sources.draft_message.client_preflight':
    'Client preflight passed. The Server will validate again.',
  'sources.draft_message.file_unsupported':
    'Only text/plain and text/markdown are active in this Section.',
  'sources.draft_message.file_size': 'The file must be between 1 byte and one MiB.',
  'sources.draft_message.file_preflight':
    'Client preflight passed. The Server will verify bytes, type and filename.',
  'sources.draft_message.url_accepted':
    'Descriptor accepted locally. The Server will perform acquisition and SSRF validation.',
  'sources.draft_message.url_invalid': 'Enter an absolute HTTP(S) URL.',
  'sources.adding_draft': 'Adding draft…',
  'sources.submitting_drafts': 'Submitting drafts…',
  'sources.input_type': 'Input type',
  'sources.label': 'Label',
  'sources.classification': 'Source classification',
  'sources.classification_help':
    'This is a classification request for this new Source. The Server validates and stores the final classification; it does not change your access clearance.',
  'sources.add_intake_draft': 'Add intake draft',
  'sources.intake_drafts': 'Intake drafts',
  'sources.requested_classification': 'Requested classification:',
  'sources.remove': 'Remove',
  'sources.discard_all': 'Discard all drafts',
  'sources.submit_drafts': 'Submit drafts',
  'sources.submission': 'Submission',
  'sources.submission_id': 'Submission ID',
  'sources.submission_items': 'Submission items',
  'sources.review_duplicate': 'Review duplicate',
  'sources.retry_same': 'Retry same context',
  'sources.retry_policy': 'Retry current policy',
  'sources.cancel_submission': 'Cancel submission',
  'sources.exact_duplicate_decision': 'Exact duplicate decision',
  'sources.existing_source': 'Existing Source:',
  'sources.version': 'Version',
  'sources.offline_cached':
    'Offline. A previously authorized cached Library may be shown, but Server search and intake actions are blocked.',
  'sources.library_stale': 'This Library snapshot is stale.',
  'sources.list': 'Sources',
  'source_detail.eyebrow': 'Source detail',
  'source_detail.loading': 'Loading Source…',
  'source_detail.back': 'Back to Source Library',
  'source_detail.return_citation': 'Return to cited resource',
  'source_detail.return_knowledge': 'Return to Knowledge resource',
  'source_detail.version': 'Version',
  'source_detail.selected': 'Selected',
  'source_detail.preview': 'Preview',
  'source_detail.questions': 'Questions',
  'source_detail.original_preview': 'Original Preview',
  'source_detail.loading_preview': 'Loading Preview…',
  'source_detail.preview_unsupported':
    'Original bytes are available, but inline Preview is not supported for this media type.',
  'source_detail.evidence': 'Evidence',
  'source_detail.loading_evidence': 'Loading Evidence…',
  'source_detail.no_evidence': 'No Evidence is indexed yet.',
  'source_detail.version_history': 'Version history',
  'source_detail.loading_history': 'Loading Version history…',
  'source_detail.evidence_id': 'Evidence ID',
  'source_detail.evidence_revision': 'Evidence revision',
  'source_detail.source_id': 'Source ID',
  'source_detail.source_version_id': 'SourceVersion ID',
  'enum.ask_mode.canonical_only': 'Verified knowledge only',
  'enum.ask_mode.source_exploration': 'Use selected sources',
  'enum.ask_mode.hybrid': 'Verified knowledge + selected sources',
  'enum.ask_mode.unknown': 'Ask with the selected context',
  'enum.source_preview.not_ready': 'Preview not ready',
  'enum.source_preview.processing': 'Preparing preview',
  'enum.source_preview.ready': 'Preview ready',
  'enum.source_preview.failed': 'Preview unavailable',
  'enum.source_preview.access_restricted': 'Preview access restricted',
  'enum.source_preview.unknown': 'Preview status unavailable',
  'enum.source_ask.not_ready': 'Not yet available for questions',
  'enum.source_ask.source_version_ready': 'Available for questions',
  'enum.source_ask.evidence_ready': 'Available with indexed evidence',
  'enum.source_ask.action_required': 'Needs attention before use',
  'enum.source_ask.failed': 'Unavailable for questions',
  'enum.source_ask.access_restricted': 'Question access restricted',
  'enum.source_ask.unknown': 'Question availability unknown',
  'enum.intake_state.validating': 'Checking',
  'enum.intake_state.queued': 'Queued',
  'enum.intake_state.running': 'Processing',
  'enum.intake_state.partial': 'Partially completed',
  'enum.intake_state.action_required': 'Needs attention',
  'enum.intake_state.succeeded': 'Completed',
  'enum.intake_state.failed': 'Failed',
  'enum.intake_state.cancel_requested': 'Cancellation requested',
  'enum.intake_state.cancelled': 'Cancelled',
  'enum.intake_state.outcome_indeterminate': 'Checking final outcome',
  'enum.intake_state.unknown': 'Status unavailable',
  'enum.intake_kind.direct_text': 'Direct Text',
  'enum.intake_kind.file': 'File',
  'enum.intake_kind.url': 'URL',
  'enum.intake_kind.unknown': 'Source',
  'enum.intake_validation.ready': 'Ready to submit',
  'enum.intake_validation.unsupported_format': 'Unsupported format',
  'enum.intake_validation.encrypted': 'Encrypted content',
  'enum.intake_validation.corrupt': 'Unreadable content',
  'enum.intake_validation.inaccessible': 'Cannot be accessed',
  'enum.intake_validation.policy_blocked': 'Blocked by policy',
  'enum.intake_validation.too_large': 'File is too large',
  'enum.intake_validation.invalid_filename': 'Invalid file name',
  'enum.intake_validation.invalid_url': 'Invalid URL',
  'enum.intake_validation.unsafe_destination': 'Unsafe destination',
  'enum.intake_validation.unknown': 'Check required',
  'enum.duplicate.reuse': 'Use the existing version',
  'enum.duplicate.version_candidate': 'Create a new version candidate',
  'enum.duplicate.separate_source': 'Create a separate source',
  'enum.duplicate.cancel': 'Cancel this submission',
  'enum.duplicate.unknown': 'Resolve duplicate',
  'enum.answer_run.queued': 'Queued',
  'enum.answer_run.running': 'Answering',
  'enum.answer_run.action_required': 'Needs attention',
  'enum.answer_run.succeeded': 'Completed',
  'enum.answer_run.failed': 'Failed',
  'enum.answer_run.cancel_requested': 'Cancellation requested',
  'enum.answer_run.cancelled': 'Cancelled',
  'enum.answer_run.outcome_unknown': 'Checking final outcome',
  'enum.answer_run.unknown': 'Answer status unavailable',
  'enum.transformation.not_started': 'Not processed yet',
  'enum.transformation.running': 'Processing',
  'enum.transformation.ready': 'Ready',
  'enum.transformation.failed': 'Processing failed',
  'enum.transformation.unknown': 'Processing status unavailable',
  'enum.evidence_origin.original': 'Original source',
  'enum.evidence_origin.translation': 'Translation',
  'enum.evidence_origin.summary': 'Summary',
  'enum.evidence_origin.annotation': 'Annotation',
  'enum.evidence_origin.ai_output': 'AI output',
  'enum.evidence_origin.unknown': 'Source evidence',
  'enum.media_type.text': 'Text',
  'enum.media_type.markdown': 'Markdown',
  'enum.media_type.pdf': 'PDF',
  'enum.media_type.web': 'Web page',
  'enum.media_type.image': 'Image',
  'enum.media_type.document': 'Document',
  'enum.sensitivity.public': 'Public',
  'enum.sensitivity.internal': 'Internal',
  'enum.sensitivity.private': 'Private',
  'enum.sensitivity.unknown': 'Unclassified',
} as const;

type ProductMessageKey = keyof typeof enUS;

const koKR: Record<ProductMessageKey, string> = {
  'common.close': '닫기',
  'common.save': '저장',
  'common.cancel': '취소',
  'common.saving': '저장 중...',
  'common.checking': '확인 중...',
  'common.check_result': '결과 확인',
  'common.loading_preferences': '환경설정을 불러오는 중...',
  'shell.current_project': '현재 프로젝트',
  'shell.not_created': '생성되지 않음',
  'shell.primary_navigation': '주 탐색',
  'shell.mobile_navigation': '모바일 탐색',
  'shell.offline':
    '오프라인입니다. 캐시 정보가 오래되었을 수 있으며 서버 작업과 검색은 사용할 수 없습니다.',
  'shell.additional_states': '추가 상태',
  'nav.home': '홈',
  'nav.sources': '소스',
  'nav.ask': '질문',
  'nav.available': '사용 가능',
  'nav.coming_later': '추후 제공',
  'nav.temporarily_unavailable': '일시적으로 사용할 수 없음',
  'nav.access_restricted': '접근 제한',
  'home.first_run': '첫 실행',
  'home.create_first_project': '첫 프로젝트를 만드세요',
  'home.create_first_project_help': '시작하려면 첫 프로젝트를 만드세요.',
  'home.open_onboarding': '프로젝트 시작 설정 열기',
  'home.action_center': '작업 센터',
  'home.primary_actions': '주요 작업',
  'home.attention': '확인 필요',
  'home.continue_working': '계속 작업',
  'home.recent_and_pinned': '최근 및 고정',
  'commands.title': '명령',
  'commands.help': '이름, 별칭 또는 키워드로 명령을 찾으세요.',
  'commands.search_label': '명령 검색',
  'commands.no_match': '일치하는 명령이 없습니다.',
  'commands.category.help': '도움말',
  'commands.category.search': '검색',
  'commands.category.project': '프로젝트',
  'commands.category.answer': '답변',
  'commands.category.ai': 'AI',
  'commands.category.privacy': '개인정보',
  'commands.category.preferences': '환경설정',
  'commands.category.navigation': '탐색',
  'commands.category.inspection': '점검',
  'preferences.locale_title': '언어 환경설정',
  'preferences.timezone_title': '시간대 환경설정',
  'preferences.display_title': '화면 환경설정',
  'preferences.locale': '언어',
  'technical.title': '기술 정보',
  'privacy.review_title': '개인정보 검토',
  'privacy.project_title': '프로젝트 개인정보',
  'privacy.loading': '개인정보 설정을 불러오는 중...',
  'privacy.open_review': '개인정보 검토 열기',
  'privacy.request_review': '외부 AI 전송 검토 요청',
  'privacy.approve_review': '검토된 개인정보 제안 승인',
  'ai.configure': 'AI 구성',
  'ai.test': 'AI 연결 테스트',
  'ai.loading': 'AI 설정을 불러오는 중...',
  'ai.provider': '제공자',
  'ai.model': '모델',
  'ai.api_key': 'API 키 (쓰기 전용)',
  'ai.test_connection': '연결 테스트',
  'ai.testing': '테스트 중...',
  'ai.save_configuration': 'AI 구성 저장',
  'ai.provider_privacy': '제공자 개인정보',
  'ai.credential_actions': '자격 증명 작업',
  'project.manage': '프로젝트 관리',
  'project.create': '프로젝트 만들기',
  'project.rename': '프로젝트 이름 바꾸기',
  'project.restore': '프로젝트 복원',
  'project.archive': '프로젝트 보관',
  'project.delete_request': '프로젝트 삭제 요청',
  'project.loading': '프로젝트를 불러오는 중…',
  'project.active': '현재 프로젝트',
  'project.rename_action': '이름 바꾸기',
  'project.archive_action': '보관',
  'project.restore_action': '복원',
  'project.request_deletion': '삭제 요청',
  'project.creating': '생성 중…',
  'project.restoring': '복원 중…',
  'project.submitting': '제출 중…',
  'project.confirm_archive': '보관 확인',
  'project.confirm_deletion': '삭제 요청 확인',
  'search.title': '검색',
  'search.query': '검색어',
  'search.scope': '검색 범위',
  'search.active_project': '현재 프로젝트',
  'search.selected_projects': '선택한 프로젝트',
  'search.submit': '검색',
  'search.searching': '검색 중...',
  'search.loading': '선택한 프로젝트 범위에서 검색 중...',
  'search.no_results': '선택한 프로젝트 범위에 결과가 없습니다.',
  'search.active_results': '현재 프로젝트의 결과입니다.',
  'search.cross_results': '선택한 접근 가능 프로젝트의 결과입니다.',
  'search.results_label': '검색 결과',
  'ask.eyebrow': '지식 질문',
  'ask.title': '질문',
  'ask.question_draft': '질문 초안',
  'ask.draft_help': '제출하기 전까지 질문은 여기에 유지됩니다.',
  'ask.question': '질문',
  'ask.submit': '질문 제출',
  'ask.submitting': '제출 중...',
  'ask.conversations': '대화',
  'ask.no_conversations': '아직 대화가 없습니다.',
  'ask.answer': '답변',
  'ask.answer_actions': '답변 작업',
  'ask.selected_conversation': '선택한 대화',
  'ask.partial_answer': '부분 답변',
  'ask.open_evidence': '고정된 근거 열기',
  'ask.answer_status': '답변 상태',
  'ask.cancel_answer': '답변 취소',
  'ask.answer_export': '답변 내보내기 결과',
  'ask.create_or_select_project': '질문하려면 프로젝트를 만들거나 선택하세요.',
  'ask.loading_workspace': '질문 작업공간을 불러오는 중…',
  'ask.mode': '질문 방식',
  'ask.source_context': '소스 범위',
  'ask.source_selection_unavailable': '이 질문 범위에서는 소스를 선택할 수 없습니다.',
  'ask.loading_sources': '소스를 불러오는 중…',
  'ask.sources_load_failed': '소스를 불러오지 못했습니다.',
  'ask.source_project_mismatch': '소스 라이브러리 프로젝트가 이 질문 항목과 일치하지 않습니다.',
  'ask.no_sources': '이 프로젝트에서 질문에 사용할 수 있는 소스가 없습니다.',
  'ask.pinned_version': '고정된 버전',
  'ask.version': '버전',
  'ask.check_submission_outcome': '제출 결과 확인',
  'ask.source_selection_required': '선택한 소스를 사용하려면 소스를 하나 이상 선택하세요.',
  'ask.action_required': '조치 필요:',
  'ask.review_privacy': '개인정보 검토',
  'ask.provider_eligibility_unavailable':
    '제공자 사용 가능 여부를 확인하지 못했습니다. 질문을 제출할 수 없습니다.',
  'ask.submission_unavailable': '이 대화에서는 질문을 제출할 수 없습니다.',
  'ask.current_conversation': '(현재 대화)',
  'ask.conversation_list': '대화',
  'ask.submission_rejected': '질문 제출이 거부되었습니다. 초안은 유지되었습니다.',
  'ask.submission_outcome_unknown':
    '제출 결과를 아직 확인할 수 없습니다. 기존 요청 식별자와 초안은 유지되었습니다.',
  'ask.checking_submission_outcome': '기존 제출 결과를 확인하는 중…',
  'ask.answer_result_unknown': '답변 결과를 확인할 수 없습니다. 다시 시도하기 전에 확인하세요.',
  'ask.answer_result_still_unknown':
    '답변 결과를 아직 확인할 수 없습니다. 새 요청을 보내지 말고 다시 확인하세요.',
  'ask.request_rejected': '요청이 거부되었습니다. 새 요청은 보내지 않았습니다.',
  'ask.request_pending':
    '요청이 접수되었지만 완료되지 않았습니다. 자동 재시도는 시작하지 않았습니다.',
  'ask.result_unavailable':
    '요청은 완료되었지만 결과를 아직 사용할 수 없습니다. 새 요청을 보내지 말고 다시 확인하세요.',
  'ask.answer_request_recovered': '완료된 답변 요청과 결과를 복구했습니다.',
  'ask.answer_cancel_requested': '답변 취소를 요청했습니다.',
  'ask.answer_retry_accepted': '새 시도로 답변 재시도가 접수되었습니다.',
  'ask.answer_export_completed': '답변 내보내기가 완료되었습니다.',
  'ask.transition_proposed': '초안 전환을 제안했습니다. 검증된 지식은 변경하지 않았습니다.',
  'ask.source_id': '소스 ID',
  'ask.source_version_id': '소스 버전 ID',
  'ask.failure_code': '실패 코드',
  'answer.export': '답변 내보내기',
  'answer.retry': '답변 다시 시도',
  'answer.applies_selected': '이 작업은 선택한 답변에 적용됩니다.',
  'answer.retry_same': '같은 조건으로 다시 시도',
  'answer.retry_policy': '현재 정책으로 다시 시도',
  'answer.propose_intake': '수집 초안 제안',
  'answer.propose_change': '변경 초안 제안',
  'answer.propose_directive': '지시문 제안',
  'sources.title': '소스',
  'sources.eyebrow': '지식 입력',
  'sources.create_project': '소스를 추가하기 전에 프로젝트를 만드세요',
  'sources.create_project_help': '소스를 정리하고 추가하려면 프로젝트를 만드세요.',
  'sources.draft_queue': '초안 대기열',
  'sources.draft_help': '초안은 제출하거나 버릴 때까지 생성한 프로젝트에 유지됩니다.',
  'sources.no_drafts': '아직 초안이 없습니다.',
  'sources.library': '소스 라이브러리',
  'sources.search': '소스 검색',
  'sources.search_submit': '검색',
  'sources.loading_library': '소스 라이브러리를 불러오는 중…',
  'sources.no_matching': '일치하는 소스가 없습니다',
  'sources.none_yet': '아직 소스가 없습니다',
  'sources.change_search': '서버 검색어를 변경하거나 지우세요.',
  'sources.submitted_appear': '제출한 소스는 서버 처리 후 여기에 표시됩니다.',
  'sources.open': '소스 열기',
  'sources.unavailable': '이 소스를 사용할 수 없습니다.',
  'sources.needs_attention': '이 소스를 사용하려면 확인이 필요합니다.',
  'sources.question_access_restricted': '질문 사용 접근이 제한되었습니다.',
  'sources.questions_not_ready': '아직 질문에 사용할 수 없습니다.',
  'sources.preview_unavailable': '미리보기를 사용할 수 없습니다.',
  'sources.choose_file_again': '제출하기 전에 파일을 다시 선택하세요.',
  'sources.submission_failed': '소스 제출에 실패했습니다.',
  'sources.duplicate_decision_failed': '중복 항목 결정을 불러오지 못했습니다.',
  'sources.duplicate_resolution_failed': '중복 항목 처리를 완료하지 못했습니다.',
  'sources.cancellation_failed': '취소에 실패했습니다.',
  'sources.retry_failed': '다시 시도하지 못했습니다.',
  'sources.project_mismatch':
    '현재 프로젝트가 변경되었습니다. 이 초안은 원래 프로젝트에 격리되어 있으며 현재 범위에서는 제출할 수 없습니다.',
  'sources.invalid_draft': '이 초안을 열 수 없습니다. 내용을 확인한 후 다시 시도하세요.',
  'sources.draft_message.seeded_text_review': '제출하기 전에 생성된 직접 입력 내용을 검토하세요.',
  'sources.draft_message.seeded_text_too_large':
    '생성된 직접 입력 내용이 현재 1 MiB 한도를 초과합니다.',
  'sources.draft_message.seeded_url_validation':
    '제출할 때 서버가 URL 안전성 검증을 다시 수행합니다.',
  'sources.draft_message.seed_file_reselect':
    '파일을 다시 선택하세요. 생성된 초안은 브라우저 파일 바이트를 제공할 수 없습니다.',
  'sources.draft_message.direct_text_empty': '직접 입력 내용은 비워 둘 수 없습니다.',
  'sources.draft_message.direct_text_too_large': '직접 입력 내용이 현재 1 MiB 한도를 초과합니다.',
  'sources.draft_message.client_preflight':
    '클라이언트 사전 검사를 통과했습니다. 서버가 다시 검증합니다.',
  'sources.draft_message.file_unsupported':
    '이 섹션에서는 text/plain 및 text/markdown 형식만 사용할 수 있습니다.',
  'sources.draft_message.file_size': '파일 크기는 1바이트 이상 1 MiB 이하여야 합니다.',
  'sources.draft_message.file_preflight':
    '클라이언트 사전 검사를 통과했습니다. 서버가 바이트, 형식 및 파일 이름을 검증합니다.',
  'sources.draft_message.url_accepted':
    '로컬에서 설명자를 접수했습니다. 서버가 가져오기와 SSRF 검증을 수행합니다.',
  'sources.draft_message.url_invalid': '절대 HTTP(S) URL을 입력하세요.',
  'sources.adding_draft': '초안 추가 중…',
  'sources.submitting_drafts': '초안 제출 중…',
  'sources.input_type': '입력 유형',
  'sources.label': '이름',
  'sources.classification': '소스 분류',
  'sources.classification_help':
    '새 소스에 대한 분류 요청입니다. 서버가 최종 분류를 검증하고 저장하며 사용자의 접근 허용 수준은 변경하지 않습니다.',
  'sources.add_intake_draft': '수집 초안 추가',
  'sources.intake_drafts': '수집 초안',
  'sources.requested_classification': '요청한 분류:',
  'sources.remove': '제거',
  'sources.discard_all': '모든 초안 버리기',
  'sources.submit_drafts': '초안 제출',
  'sources.submission': '제출',
  'sources.submission_id': '제출 ID',
  'sources.submission_items': '제출 항목',
  'sources.review_duplicate': '중복 항목 검토',
  'sources.retry_same': '같은 조건으로 다시 시도',
  'sources.retry_policy': '현재 정책으로 다시 시도',
  'sources.cancel_submission': '제출 취소',
  'sources.exact_duplicate_decision': '완전 중복 항목 처리',
  'sources.existing_source': '기존 소스:',
  'sources.version': '버전',
  'sources.offline_cached':
    '오프라인입니다. 이전에 허용된 라이브러리 캐시는 표시될 수 있지만 서버 검색과 수집 작업은 차단됩니다.',
  'sources.library_stale': '이 라이브러리 정보는 오래되었습니다.',
  'sources.list': '소스',
  'source_detail.eyebrow': '소스 상세',
  'source_detail.loading': '소스를 불러오는 중…',
  'source_detail.back': '소스 라이브러리로 돌아가기',
  'source_detail.return_citation': '인용한 항목으로 돌아가기',
  'source_detail.return_knowledge': '지식 항목으로 돌아가기',
  'source_detail.version': '버전',
  'source_detail.selected': '선택됨',
  'source_detail.preview': '미리보기',
  'source_detail.questions': '질문 사용',
  'source_detail.original_preview': '원본 미리보기',
  'source_detail.loading_preview': '미리보기를 불러오는 중…',
  'source_detail.preview_unsupported':
    '원본 바이트는 사용할 수 있지만 이 미디어 형식은 인라인 미리보기를 지원하지 않습니다.',
  'source_detail.evidence': '근거',
  'source_detail.loading_evidence': '근거를 불러오는 중…',
  'source_detail.no_evidence': '아직 색인된 근거가 없습니다.',
  'source_detail.version_history': '버전 기록',
  'source_detail.loading_history': '버전 기록을 불러오는 중…',
  'source_detail.evidence_id': '근거 ID',
  'source_detail.evidence_revision': '근거 리비전',
  'source_detail.source_id': '소스 ID',
  'source_detail.source_version_id': '소스 버전 ID',
  'enum.ask_mode.canonical_only': '검증된 지식만 사용',
  'enum.ask_mode.source_exploration': '선택한 소스 사용',
  'enum.ask_mode.hybrid': '검증된 지식과 선택한 소스 사용',
  'enum.ask_mode.unknown': '선택한 범위로 질문',
  'enum.source_preview.not_ready': '미리보기 준비 전',
  'enum.source_preview.processing': '미리보기 준비 중',
  'enum.source_preview.ready': '미리보기 준비됨',
  'enum.source_preview.failed': '미리보기 사용 불가',
  'enum.source_preview.access_restricted': '미리보기 접근 제한',
  'enum.source_preview.unknown': '미리보기 상태를 확인할 수 없음',
  'enum.source_ask.not_ready': '아직 질문에 사용할 수 없음',
  'enum.source_ask.source_version_ready': '질문에 사용 가능',
  'enum.source_ask.evidence_ready': '색인된 근거와 함께 사용 가능',
  'enum.source_ask.action_required': '사용 전 확인 필요',
  'enum.source_ask.failed': '질문에 사용할 수 없음',
  'enum.source_ask.access_restricted': '질문 사용 접근 제한',
  'enum.source_ask.unknown': '질문 사용 가능 여부를 확인할 수 없음',
  'enum.intake_state.validating': '확인 중',
  'enum.intake_state.queued': '대기 중',
  'enum.intake_state.running': '처리 중',
  'enum.intake_state.partial': '일부 완료',
  'enum.intake_state.action_required': '확인 필요',
  'enum.intake_state.succeeded': '완료',
  'enum.intake_state.failed': '실패',
  'enum.intake_state.cancel_requested': '취소 요청됨',
  'enum.intake_state.cancelled': '취소됨',
  'enum.intake_state.outcome_indeterminate': '최종 결과 확인 중',
  'enum.intake_state.unknown': '상태를 확인할 수 없음',
  'enum.intake_kind.direct_text': '직접 입력',
  'enum.intake_kind.file': '파일',
  'enum.intake_kind.url': 'URL',
  'enum.intake_kind.unknown': '소스',
  'enum.intake_validation.ready': '제출 준비됨',
  'enum.intake_validation.unsupported_format': '지원하지 않는 형식',
  'enum.intake_validation.encrypted': '암호화된 내용',
  'enum.intake_validation.corrupt': '읽을 수 없는 내용',
  'enum.intake_validation.inaccessible': '접근할 수 없음',
  'enum.intake_validation.policy_blocked': '정책에 의해 차단됨',
  'enum.intake_validation.too_large': '파일이 너무 큼',
  'enum.intake_validation.invalid_filename': '잘못된 파일 이름',
  'enum.intake_validation.invalid_url': '잘못된 URL',
  'enum.intake_validation.unsafe_destination': '안전하지 않은 대상',
  'enum.intake_validation.unknown': '확인 필요',
  'enum.duplicate.reuse': '기존 버전 사용',
  'enum.duplicate.version_candidate': '새 버전 후보 만들기',
  'enum.duplicate.separate_source': '별도 소스 만들기',
  'enum.duplicate.cancel': '이 제출 취소',
  'enum.duplicate.unknown': '중복 항목 처리',
  'enum.answer_run.queued': '대기 중',
  'enum.answer_run.running': '답변 중',
  'enum.answer_run.action_required': '확인 필요',
  'enum.answer_run.succeeded': '완료',
  'enum.answer_run.failed': '실패',
  'enum.answer_run.cancel_requested': '취소 요청됨',
  'enum.answer_run.cancelled': '취소됨',
  'enum.answer_run.outcome_unknown': '최종 결과 확인 중',
  'enum.answer_run.unknown': '답변 상태를 확인할 수 없음',
  'enum.transformation.not_started': '아직 처리되지 않음',
  'enum.transformation.running': '처리 중',
  'enum.transformation.ready': '준비됨',
  'enum.transformation.failed': '처리 실패',
  'enum.transformation.unknown': '처리 상태를 확인할 수 없음',
  'enum.evidence_origin.original': '원본 소스',
  'enum.evidence_origin.translation': '번역',
  'enum.evidence_origin.summary': '요약',
  'enum.evidence_origin.annotation': '주석',
  'enum.evidence_origin.ai_output': 'AI 결과',
  'enum.evidence_origin.unknown': '소스 근거',
  'enum.media_type.text': '텍스트',
  'enum.media_type.markdown': '마크다운',
  'enum.media_type.pdf': 'PDF',
  'enum.media_type.web': '웹 페이지',
  'enum.media_type.image': '이미지',
  'enum.media_type.document': '문서',
  'enum.sensitivity.public': '공개',
  'enum.sensitivity.internal': '내부',
  'enum.sensitivity.private': '비공개',
  'enum.sensitivity.unknown': '미분류',
};

const dictionaries: Record<ProductLocale, Record<ProductMessageKey, string>> = {
  'en-US': enUS,
  'ko-KR': koKR,
};

export type ProductTranslator = (key: ProductMessageKey) => string;

export type HfmOwnerLabelKind =
  | 'askMode'
  | 'sourcePreview'
  | 'sourceAskUsage'
  | 'intakeState'
  | 'intakeKind'
  | 'intakeValidation'
  | 'duplicateDisposition'
  | 'answerRun'
  | 'transformationState'
  | 'evidenceOrigin'
  | 'mediaType'
  | 'sensitivity';

const hfmOwnerLabelKeys: Readonly<
  Record<HfmOwnerLabelKind, Readonly<Record<string, ProductMessageKey>>>
> = {
  askMode: {
    CANONICAL_ONLY: 'enum.ask_mode.canonical_only',
    SOURCE_EXPLORATION: 'enum.ask_mode.source_exploration',
    HYBRID: 'enum.ask_mode.hybrid',
  },
  sourcePreview: {
    NOT_READY: 'enum.source_preview.not_ready',
    PROCESSING: 'enum.source_preview.processing',
    READY: 'enum.source_preview.ready',
    FAILED: 'enum.source_preview.failed',
    ACCESS_RESTRICTED: 'enum.source_preview.access_restricted',
  },
  sourceAskUsage: {
    NOT_READY: 'enum.source_ask.not_ready',
    SOURCE_VERSION_READY: 'enum.source_ask.source_version_ready',
    EVIDENCE_READY: 'enum.source_ask.evidence_ready',
    ACTION_REQUIRED: 'enum.source_ask.action_required',
    FAILED: 'enum.source_ask.failed',
    ACCESS_RESTRICTED: 'enum.source_ask.access_restricted',
  },
  intakeState: {
    VALIDATING: 'enum.intake_state.validating',
    QUEUED: 'enum.intake_state.queued',
    RUNNING: 'enum.intake_state.running',
    PARTIAL: 'enum.intake_state.partial',
    ACTION_REQUIRED: 'enum.intake_state.action_required',
    SUCCEEDED: 'enum.intake_state.succeeded',
    FAILED: 'enum.intake_state.failed',
    CANCEL_REQUESTED: 'enum.intake_state.cancel_requested',
    CANCELLED: 'enum.intake_state.cancelled',
    OUTCOME_INDETERMINATE: 'enum.intake_state.outcome_indeterminate',
  },
  intakeKind: {
    DIRECT_TEXT: 'enum.intake_kind.direct_text',
    FILE: 'enum.intake_kind.file',
    FILE_METADATA: 'enum.intake_kind.file',
    URL: 'enum.intake_kind.url',
  },
  intakeValidation: {
    READY: 'enum.intake_validation.ready',
    VALID: 'enum.intake_validation.ready',
    UNSUPPORTED_FORMAT: 'enum.intake_validation.unsupported_format',
    ENCRYPTED: 'enum.intake_validation.encrypted',
    CORRUPT: 'enum.intake_validation.corrupt',
    INACCESSIBLE: 'enum.intake_validation.inaccessible',
    POLICY_BLOCKED: 'enum.intake_validation.policy_blocked',
    TOO_LARGE: 'enum.intake_validation.too_large',
    INVALID_FILENAME: 'enum.intake_validation.invalid_filename',
    INVALID_URL: 'enum.intake_validation.invalid_url',
    UNSAFE_DESTINATION: 'enum.intake_validation.unsafe_destination',
  },
  duplicateDisposition: {
    REUSE_EXISTING_VERSION: 'enum.duplicate.reuse',
    CREATE_VERSION_CANDIDATE: 'enum.duplicate.version_candidate',
    CREATE_SEPARATE_SOURCE: 'enum.duplicate.separate_source',
    CANCEL_SUBMISSION: 'enum.duplicate.cancel',
  },
  answerRun: {
    QUEUED: 'enum.answer_run.queued',
    RUNNING: 'enum.answer_run.running',
    STREAMING: 'enum.answer_run.running',
    ACTION_REQUIRED: 'enum.answer_run.action_required',
    SUCCEEDED: 'enum.answer_run.succeeded',
    FAILED: 'enum.answer_run.failed',
    CANCEL_REQUESTED: 'enum.answer_run.cancel_requested',
    CANCELLED: 'enum.answer_run.cancelled',
    OUTCOME_UNKNOWN: 'enum.answer_run.outcome_unknown',
  },
  transformationState: {
    NOT_STARTED: 'enum.transformation.not_started',
    RUNNING: 'enum.transformation.running',
    READY: 'enum.transformation.ready',
    FAILED: 'enum.transformation.failed',
  },
  evidenceOrigin: {
    ORIGINAL: 'enum.evidence_origin.original',
    TRANSLATION: 'enum.evidence_origin.translation',
    SUMMARY: 'enum.evidence_origin.summary',
    ANNOTATION: 'enum.evidence_origin.annotation',
    AI_OUTPUT: 'enum.evidence_origin.ai_output',
  },
  mediaType: {
    'text/plain': 'enum.media_type.text',
    'text/markdown': 'enum.media_type.markdown',
    'application/pdf': 'enum.media_type.pdf',
    'text/html': 'enum.media_type.web',
  },
  sensitivity: {
    public: 'enum.sensitivity.public',
    internal: 'enum.sensitivity.internal',
    private: 'enum.sensitivity.private',
  },
};

const hfmOwnerFallbackKeys: Readonly<Record<HfmOwnerLabelKind, ProductMessageKey>> = {
  askMode: 'enum.ask_mode.unknown',
  sourcePreview: 'enum.source_preview.unknown',
  sourceAskUsage: 'enum.source_ask.unknown',
  intakeState: 'enum.intake_state.unknown',
  intakeKind: 'enum.intake_kind.unknown',
  intakeValidation: 'enum.intake_validation.unknown',
  duplicateDisposition: 'enum.duplicate.unknown',
  answerRun: 'enum.answer_run.unknown',
  transformationState: 'enum.transformation.unknown',
  evidenceOrigin: 'enum.evidence_origin.unknown',
  mediaType: 'enum.media_type.document',
  sensitivity: 'enum.sensitivity.unknown',
};

export const hfmOwnerLabel = (
  t: ProductTranslator,
  kind: HfmOwnerLabelKind,
  value: string,
): string => {
  const key = hfmOwnerLabelKeys[kind][value];
  if (key) return t(key);
  if (kind === 'mediaType' && value.startsWith('image/')) return t('enum.media_type.image');
  return t(hfmOwnerFallbackKeys[kind]);
};

export const resolveProductLocale = (value: unknown): ProductLocale =>
  value === 'ko-KR' || value === 'en-US' ? value : 'en-US';

type ProductLocalizationValue = {
  readonly locale: ProductLocale;
  readonly t: ProductTranslator;
};

const defaultLocalization: ProductLocalizationValue = {
  locale: 'en-US',
  t: (key) => enUS[key],
};

const ProductLocalizationContext = createContext<ProductLocalizationValue>(defaultLocalization);

export const ProductLocalizationProvider = ({
  children,
  principalId,
}: {
  readonly children: ReactNode;
  readonly principalId: string;
}) => {
  const { apiClient } = useAppRuntime();
  const preferences = useQuery({
    queryKey: principalPreferencesQueryKey(principalId),
    queryFn: () => apiClient.getPrincipalPreferences(),
    staleTime: Number.POSITIVE_INFINITY,
  });
  const locale = resolveProductLocale(preferences.data?.preferences['locale']);
  const value = useMemo<ProductLocalizationValue>(
    () => ({ locale, t: (key) => dictionaries[locale][key] }),
    [locale],
  );

  if (preferences.isPending) {
    return <p role="status">{enUS['common.loading_preferences']}</p>;
  }

  return (
    <ProductLocalizationContext.Provider value={value}>
      {children}
    </ProductLocalizationContext.Provider>
  );
};

export const useProductLocalization = (): ProductLocalizationValue =>
  useContext(ProductLocalizationContext);
