import { useQuery } from '@tanstack/react-query';
import { createContext, useContext, useMemo, type ReactNode } from 'react';

import { useAppRuntime } from '../app/providers.js';
import { principalPreferencesQueryKey } from '../app/query-keys.js';

export type ProductLocale = 'ko-KR' | 'en-US';

const enUS = {
  'common.close': 'Close',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.saving': 'Saving...',
  'common.checking': 'Checking...',
  'common.check_result': 'Check result',
  'common.loading_preferences': 'Loading preferences...',
  'shell.current_project': 'Current project',
  'shell.not_created': 'Not created',
  'shell.primary_navigation': 'Primary navigation',
  'shell.mobile_navigation': 'Mobile navigation',
  'shell.offline':
    'Offline. Cached information may be stale; server actions and Search are disabled.',
  'nav.home': 'Home',
  'nav.sources': 'Sources',
  'nav.ask': 'Ask',
  'nav.available': 'Available',
  'nav.coming_later': 'Coming later',
  'nav.temporarily_unavailable': 'Temporarily unavailable',
  'nav.access_restricted': 'Access restricted',
  'home.first_run': 'First run',
  'home.create_first_project': 'Create your first Project',
  'home.create_first_project_help': 'Create your first Project to get started.',
  'home.open_onboarding': 'Open Project onboarding',
  'home.action_center': 'Action Center',
  'home.primary_actions': 'Primary Actions',
  'home.attention': 'Attention',
  'home.continue_working': 'Continue Working',
  'home.recent_and_pinned': 'Recent and Pinned',
  'commands.title': 'Commands',
  'commands.help': 'Find a command by name, alias, or keyword.',
  'commands.search_label': 'Command search',
  'commands.no_match': 'No matching commands.',
  'commands.category.help': 'Help',
  'commands.category.search': 'Search',
  'commands.category.project': 'Project',
  'commands.category.answer': 'Answer',
  'commands.category.ai': 'AI',
  'commands.category.privacy': 'Privacy',
  'commands.category.preferences': 'Preferences',
  'commands.category.navigation': 'Navigation',
  'commands.category.inspection': 'Inspection',
  'preferences.locale_title': 'Locale Preferences',
  'preferences.timezone_title': 'Timezone Preferences',
  'preferences.display_title': 'Display Preferences',
  'preferences.locale': 'Locale',
  'technical.title': 'Technical information',
  'privacy.review_title': 'Review Privacy',
  'privacy.project_title': 'Project Privacy',
  'privacy.loading': 'Loading privacy settings...',
  'privacy.open_review': 'Open privacy review',
  'privacy.request_review': 'Request external AI transfer review',
  'privacy.approve_review': 'Approve reviewed privacy proposal',
  'ai.configure': 'Configure AI',
  'ai.test': 'Test AI Connection',
  'ai.loading': 'Loading AI settings...',
  'ai.provider': 'Provider',
  'ai.model': 'Model',
  'ai.api_key': 'API Key (write-only)',
  'ai.test_connection': 'Test Connection',
  'ai.testing': 'Testing...',
  'ai.save_configuration': 'Save AI configuration',
  'ai.provider_privacy': 'Provider privacy',
  'ai.credential_actions': 'Credential actions',
  'project.manage': 'Manage Projects',
  'project.create': 'Create Project',
  'project.rename': 'Rename Project',
  'project.restore': 'Restore Project',
  'project.archive': 'Archive Project',
  'project.delete_request': 'Request Project Deletion',
  'project.loading': 'Loading Projects…',
  'project.active': 'Active Project',
  'project.rename_action': 'Rename',
  'project.archive_action': 'Archive',
  'project.restore_action': 'Restore',
  'project.request_deletion': 'Request deletion',
  'project.creating': 'Creating…',
  'project.restoring': 'Restoring…',
  'project.submitting': 'Submitting…',
  'project.confirm_archive': 'Confirm Archive',
  'project.confirm_deletion': 'Confirm Deletion Request',
  'search.title': 'Search',
  'search.query': 'Search query',
  'search.scope': 'Search scope',
  'search.active_project': 'Active Project',
  'search.selected_projects': 'Selected Projects',
  'search.submit': 'Search',
  'search.searching': 'Searching...',
  'search.loading': 'Searching the selected Project scope...',
  'search.no_results': 'No results in the selected Project scope.',
  'search.active_results': 'Results from the active Project.',
  'search.cross_results': 'Results from the selected accessible Projects.',
  'search.results_label': 'Search results',
  'ask.eyebrow': 'Knowledge question',
  'ask.title': 'Ask',
  'ask.question_draft': 'Question Draft',
  'ask.draft_help': 'Your question stays here until you submit it.',
  'ask.question': 'Question',
  'ask.submit': 'Submit question',
  'ask.submitting': 'Submitting...',
  'ask.conversations': 'Conversations',
  'ask.no_conversations': 'No conversations yet.',
  'ask.answer': 'Answer',
  'ask.answer_actions': 'Answer actions',
  'ask.selected_conversation': 'Selected conversation',
  'ask.partial_answer': 'Partial answer',
  'ask.open_evidence': 'Open pinned Evidence',
  'ask.answer_status': 'Answer status',
  'ask.cancel_answer': 'Cancel answer',
  'ask.answer_export': 'Answer export',
  'answer.export': 'Export answer',
  'answer.retry': 'Retry answer',
  'answer.applies_selected': 'This action applies to the selected answer.',
  'answer.retry_same': 'Retry same context',
  'answer.retry_policy': 'Retry current policy',
  'answer.propose_intake': 'Propose Intake Draft',
  'answer.propose_change': 'Propose Draft ChangeSet',
  'answer.propose_directive': 'Propose Directive',
  'sources.title': 'Sources',
  'sources.eyebrow': 'Knowledge input',
  'sources.create_project': 'Create a Project before adding Sources',
  'sources.create_project_help': 'Create a Project to organize and add Sources.',
  'sources.draft_queue': 'Draft Queue',
  'sources.draft_help':
    'Drafts stay with the project where they were created until submitted or discarded.',
  'sources.no_drafts': 'No drafts yet.',
  'sources.library': 'Source Library',
  'sources.search': 'Search Sources',
  'sources.search_submit': 'Search',
  'sources.loading_library': 'Loading Source Library…',
  'sources.no_matching': 'No matching Sources',
  'sources.none_yet': 'No Sources yet',
  'sources.change_search': 'Change the Server search query or clear it.',
  'sources.submitted_appear': 'Submitted Sources will appear here after Server processing.',
  'sources.open': 'Open source',
  'source_detail.eyebrow': 'Source detail',
  'source_detail.loading': 'Loading Source…',
  'source_detail.back': 'Back to Source Library',
  'source_detail.return_citation': 'Return to cited resource',
  'source_detail.return_knowledge': 'Return to Knowledge resource',
  'source_detail.version': 'Version',
  'source_detail.selected': 'Selected',
  'source_detail.preview': 'Preview',
  'source_detail.questions': 'Questions',
  'source_detail.original_preview': 'Original Preview',
  'source_detail.loading_preview': 'Loading Preview…',
  'source_detail.preview_unsupported':
    'Original bytes are available, but inline Preview is not supported for this media type.',
  'source_detail.evidence': 'Evidence',
  'source_detail.loading_evidence': 'Loading Evidence…',
  'source_detail.no_evidence': 'No Evidence is indexed yet.',
  'source_detail.version_history': 'Version history',
  'source_detail.loading_history': 'Loading Version history…',
} as const;

type ProductMessageKey = keyof typeof enUS;

const koKR: Record<ProductMessageKey, string> = {
  'common.close': '닫기',
  'common.save': '저장',
  'common.cancel': '취소',
  'common.saving': '저장 중...',
  'common.checking': '확인 중...',
  'common.check_result': '결과 확인',
  'common.loading_preferences': '환경설정을 불러오는 중...',
  'shell.current_project': '현재 프로젝트',
  'shell.not_created': '생성되지 않음',
  'shell.primary_navigation': '주 탐색',
  'shell.mobile_navigation': '모바일 탐색',
  'shell.offline':
    '오프라인입니다. 캐시 정보가 오래되었을 수 있으며 서버 작업과 검색은 사용할 수 없습니다.',
  'nav.home': '홈',
  'nav.sources': '소스',
  'nav.ask': '질문',
  'nav.available': '사용 가능',
  'nav.coming_later': '추후 제공',
  'nav.temporarily_unavailable': '일시적으로 사용할 수 없음',
  'nav.access_restricted': '접근 제한',
  'home.first_run': '첫 실행',
  'home.create_first_project': '첫 프로젝트를 만드세요',
  'home.create_first_project_help': '시작하려면 첫 프로젝트를 만드세요.',
  'home.open_onboarding': '프로젝트 시작 설정 열기',
  'home.action_center': '작업 센터',
  'home.primary_actions': '주요 작업',
  'home.attention': '확인 필요',
  'home.continue_working': '계속 작업',
  'home.recent_and_pinned': '최근 및 고정',
  'commands.title': '명령',
  'commands.help': '이름, 별칭 또는 키워드로 명령을 찾으세요.',
  'commands.search_label': '명령 검색',
  'commands.no_match': '일치하는 명령이 없습니다.',
  'commands.category.help': '도움말',
  'commands.category.search': '검색',
  'commands.category.project': '프로젝트',
  'commands.category.answer': '답변',
  'commands.category.ai': 'AI',
  'commands.category.privacy': '개인정보',
  'commands.category.preferences': '환경설정',
  'commands.category.navigation': '탐색',
  'commands.category.inspection': '점검',
  'preferences.locale_title': '언어 환경설정',
  'preferences.timezone_title': '시간대 환경설정',
  'preferences.display_title': '화면 환경설정',
  'preferences.locale': '언어',
  'technical.title': '기술 정보',
  'privacy.review_title': '개인정보 검토',
  'privacy.project_title': '프로젝트 개인정보',
  'privacy.loading': '개인정보 설정을 불러오는 중...',
  'privacy.open_review': '개인정보 검토 열기',
  'privacy.request_review': '외부 AI 전송 검토 요청',
  'privacy.approve_review': '검토된 개인정보 제안 승인',
  'ai.configure': 'AI 구성',
  'ai.test': 'AI 연결 테스트',
  'ai.loading': 'AI 설정을 불러오는 중...',
  'ai.provider': '제공자',
  'ai.model': '모델',
  'ai.api_key': 'API 키 (쓰기 전용)',
  'ai.test_connection': '연결 테스트',
  'ai.testing': '테스트 중...',
  'ai.save_configuration': 'AI 구성 저장',
  'ai.provider_privacy': '제공자 개인정보',
  'ai.credential_actions': '자격 증명 작업',
  'project.manage': '프로젝트 관리',
  'project.create': '프로젝트 만들기',
  'project.rename': '프로젝트 이름 바꾸기',
  'project.restore': '프로젝트 복원',
  'project.archive': '프로젝트 보관',
  'project.delete_request': '프로젝트 삭제 요청',
  'project.loading': '프로젝트를 불러오는 중…',
  'project.active': '현재 프로젝트',
  'project.rename_action': '이름 바꾸기',
  'project.archive_action': '보관',
  'project.restore_action': '복원',
  'project.request_deletion': '삭제 요청',
  'project.creating': '생성 중…',
  'project.restoring': '복원 중…',
  'project.submitting': '제출 중…',
  'project.confirm_archive': '보관 확인',
  'project.confirm_deletion': '삭제 요청 확인',
  'search.title': '검색',
  'search.query': '검색어',
  'search.scope': '검색 범위',
  'search.active_project': '현재 프로젝트',
  'search.selected_projects': '선택한 프로젝트',
  'search.submit': '검색',
  'search.searching': '검색 중...',
  'search.loading': '선택한 프로젝트 범위에서 검색 중...',
  'search.no_results': '선택한 프로젝트 범위에 결과가 없습니다.',
  'search.active_results': '현재 프로젝트의 결과입니다.',
  'search.cross_results': '선택한 접근 가능 프로젝트의 결과입니다.',
  'search.results_label': '검색 결과',
  'ask.eyebrow': '지식 질문',
  'ask.title': '질문',
  'ask.question_draft': '질문 초안',
  'ask.draft_help': '제출하기 전까지 질문은 여기에 유지됩니다.',
  'ask.question': '질문',
  'ask.submit': '질문 제출',
  'ask.submitting': '제출 중...',
  'ask.conversations': '대화',
  'ask.no_conversations': '아직 대화가 없습니다.',
  'ask.answer': '답변',
  'ask.answer_actions': '답변 작업',
  'ask.selected_conversation': '선택한 대화',
  'ask.partial_answer': '부분 답변',
  'ask.open_evidence': '고정된 근거 열기',
  'ask.answer_status': '답변 상태',
  'ask.cancel_answer': '답변 취소',
  'ask.answer_export': '답변 내보내기 결과',
  'answer.export': '답변 내보내기',
  'answer.retry': '답변 다시 시도',
  'answer.applies_selected': '이 작업은 선택한 답변에 적용됩니다.',
  'answer.retry_same': '같은 조건으로 다시 시도',
  'answer.retry_policy': '현재 정책으로 다시 시도',
  'answer.propose_intake': '수집 초안 제안',
  'answer.propose_change': '변경 초안 제안',
  'answer.propose_directive': '지시문 제안',
  'sources.title': '소스',
  'sources.eyebrow': '지식 입력',
  'sources.create_project': '소스를 추가하기 전에 프로젝트를 만드세요',
  'sources.create_project_help': '소스를 정리하고 추가하려면 프로젝트를 만드세요.',
  'sources.draft_queue': '초안 대기열',
  'sources.draft_help': '초안은 제출하거나 버릴 때까지 생성한 프로젝트에 유지됩니다.',
  'sources.no_drafts': '아직 초안이 없습니다.',
  'sources.library': '소스 라이브러리',
  'sources.search': '소스 검색',
  'sources.search_submit': '검색',
  'sources.loading_library': '소스 라이브러리를 불러오는 중…',
  'sources.no_matching': '일치하는 소스가 없습니다',
  'sources.none_yet': '아직 소스가 없습니다',
  'sources.change_search': '서버 검색어를 변경하거나 지우세요.',
  'sources.submitted_appear': '제출한 소스는 서버 처리 후 여기에 표시됩니다.',
  'sources.open': '소스 열기',
  'source_detail.eyebrow': '소스 상세',
  'source_detail.loading': '소스를 불러오는 중…',
  'source_detail.back': '소스 라이브러리로 돌아가기',
  'source_detail.return_citation': '인용한 항목으로 돌아가기',
  'source_detail.return_knowledge': '지식 항목으로 돌아가기',
  'source_detail.version': '버전',
  'source_detail.selected': '선택됨',
  'source_detail.preview': '미리보기',
  'source_detail.questions': '질문 사용',
  'source_detail.original_preview': '원본 미리보기',
  'source_detail.loading_preview': '미리보기를 불러오는 중…',
  'source_detail.preview_unsupported':
    '원본 바이트는 사용할 수 있지만 이 미디어 형식은 인라인 미리보기를 지원하지 않습니다.',
  'source_detail.evidence': '근거',
  'source_detail.loading_evidence': '근거를 불러오는 중…',
  'source_detail.no_evidence': '아직 색인된 근거가 없습니다.',
  'source_detail.version_history': '버전 기록',
  'source_detail.loading_history': '버전 기록을 불러오는 중…',
};

const dictionaries: Record<ProductLocale, Record<ProductMessageKey, string>> = {
  'en-US': enUS,
  'ko-KR': koKR,
};

export const resolveProductLocale = (value: unknown): ProductLocale =>
  value === 'ko-KR' || value === 'en-US' ? value : 'en-US';

type ProductLocalizationValue = {
  readonly locale: ProductLocale;
  readonly t: (key: ProductMessageKey) => string;
};

const defaultLocalization: ProductLocalizationValue = {
  locale: 'en-US',
  t: (key) => enUS[key],
};

const ProductLocalizationContext = createContext<ProductLocalizationValue>(defaultLocalization);

export const ProductLocalizationProvider = ({
  children,
  principalId,
}: {
  readonly children: ReactNode;
  readonly principalId: string;
}) => {
  const { apiClient } = useAppRuntime();
  const preferences = useQuery({
    queryKey: principalPreferencesQueryKey(principalId),
    queryFn: () => apiClient.getPrincipalPreferences(),
    staleTime: Number.POSITIVE_INFINITY,
  });
  const locale = resolveProductLocale(preferences.data?.preferences['locale']);
  const value = useMemo<ProductLocalizationValue>(
    () => ({ locale, t: (key) => dictionaries[locale][key] }),
    [locale],
  );

  if (preferences.isPending) {
    return <p role="status">{enUS['common.loading_preferences']}</p>;
  }

  return (
    <ProductLocalizationContext.Provider value={value}>
      {children}
    </ProductLocalizationContext.Provider>
  );
};

export const useProductLocalization = (): ProductLocalizationValue =>
  useContext(ProductLocalizationContext);
