import { useQuery } from '@tanstack/react-query';
import { createContext, useContext, useMemo, type ReactNode } from 'react';

import { useAppRuntime } from '../app/providers.js';
import { principalPreferencesQueryKey } from '../app/query-keys.js';

export type ProductLocale = 'ko-KR' | 'en-US';

const enUS = {
  'common.close': 'Close',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.saving': 'Saving...',
  'common.checking': 'Checking...',
  'common.check_result': 'Check result',
  'common.loading': 'Loading...',
  'common.edit': 'Edit',
  'common.retire': 'Retire',
  'common.confirm': 'Confirm',
  'common.add': 'Add',
  'common.loading_preferences': 'Loading preferences...',
  'shell.current_project': 'Current project',
  'shell.not_created': 'Not created',
  'shell.primary_navigation': 'Primary navigation',
  'shell.mobile_navigation': 'Mobile navigation',
  'shell.offline':
    'Offline. Cached information may be stale; server actions and Search are disabled.',
  'shell.additional_states': 'additional states',
  'nav.home': 'Home',
  'nav.sources': 'Sources',
  'nav.ask': 'Ask',
  'nav.available': 'Available',
  'nav.coming_later': 'Coming later',
  'nav.temporarily_unavailable': 'Temporarily unavailable',
  'nav.access_restricted': 'Access restricted',
  'home.first_run': 'First run',
  'home.create_first_project': 'Create your first Project',
  'home.create_first_project_help': 'Create your first Project to get started.',
  'home.open_onboarding': 'Open Project onboarding',
  'home.action_center': 'Action Center',
  'home.primary_actions': 'Primary Actions',
  'home.attention': 'Attention',
  'home.continue_working': 'Continue Working',
  'home.recent_and_pinned': 'Recent and Pinned',
  'home.loading': 'Loading Home Action Center…',
  'home.stale': 'This server snapshot is stale. Actions are unavailable until refresh.',
  'home.server_resources': 'Server resources',
  'home.browser_drafts': 'Browser drafts',
  'home.browser_draft_never_ranked': 'Browser draft · never server-ranked',
  'home.recent': 'Recent',
  'home.pinned': 'Pinned',
  'commands.keyboard_hint': '↑↓ Navigate · Enter Select · Esc Close',
  'global.switch.resolve_workspace': 'Resolve the current Workspace before switching Projects.',
  'global.switch.unknown_not_retried':
    'The unknown command will not be retried during the Project switch.',
  'search.result_count': '{count} search results.',
  'commands.title': 'Commands',
  'commands.help': 'Find a command by name, alias, or keyword.',
  'commands.search_label': 'Command search',
  'commands.no_match': 'No matching commands.',
  'commands.category.help': 'Help',
  'commands.category.search': 'Search',
  'commands.category.project': 'Project',
  'commands.category.answer': 'Answer',
  'commands.category.ai': 'AI',
  'commands.category.privacy': 'Privacy',
  'commands.category.preferences': 'Preferences',
  'commands.category.navigation': 'Navigation',
  'commands.category.inspection': 'Inspection',
  'preferences.locale_title': 'Locale Preferences',
  'preferences.timezone_title': 'Timezone Preferences',
  'preferences.display_title': 'Display Preferences',
  'preferences.locale': 'Locale',
  'preferences.updated': 'Preferences updated.',
  'preferences.rejected': 'Preference change was rejected.',
  'preferences.not_final': 'The preference change is not final yet. Check the result again.',
  'preferences.check_failed': 'The preference result could not be checked. Try again.',
  'preferences.timezone': 'Timezone',
  'preferences.date_format': 'Date & Time Format',
  'preferences.screen_density': 'Screen Density',
  'technical.title': 'Technical information',
  'privacy.review_title': 'Review Privacy',
  'privacy.project_title': 'Project Privacy',
  'privacy.loading': 'Loading privacy settings...',
  'privacy.open_review': 'Open privacy review',
  'privacy.request_review': 'Request external AI transfer review',
  'privacy.approve_review': 'Approve reviewed privacy proposal',
  'privacy.owner_approval_required': 'Owner approval is still required for this privacy review.',
  'privacy.project_approval_recorded':
    'Project privacy approval was recorded. Deployment policy still applies.',
  'privacy.review_not_final': 'The privacy review is not final yet. Check the result again.',
  'privacy.review_needs_checking':
    'The privacy review result needs checking. It will not be submitted again.',
  'privacy.review_completed': 'Privacy review completed.',
  'privacy.review_rejected': 'Privacy review was rejected.',
  'privacy.review_check_failed': 'The privacy review result could not be checked. Try again.',
  'privacy.load_failed': 'Failed to load privacy settings.',
  'commands.unavailable.answer_offline': 'Answer actions are unavailable while offline.',
  'commands.unavailable.ai_configuration_offline': 'AI configuration is unavailable while offline.',
  'commands.unavailable.ai_test_offline': 'AI connection test is unavailable while offline.',
  'commands.unavailable.privacy_open_offline': 'Privacy is unavailable while offline.',
  'commands.unavailable.privacy_review_offline': 'Privacy review is unavailable while offline',
  'commands.unavailable.answer_pending':
    'Check the current answer request result before starting another action.',
  'commands.unavailable.search_offline': 'Search is unavailable while offline.',
  'commands.unavailable.project_offline': 'Project controls are unavailable while offline.',
  'commands.unavailable.project_switch_offline': 'Project switching is unavailable while offline.',
  'commands.unavailable.discovery_offline':
    'Discovery owner actions are unavailable while offline.',
  'commands.unavailable.discovery_pending': 'The Discovery finding action is still processing.',
  'commands.unavailable.conflict_rules_offline': 'Conflict rules are unavailable while offline.',
  'commands.unavailable.preferences_offline': 'Preferences are unavailable while offline.',
  'commands.unavailable.preferences_project_required':
    'Preferences are unavailable until a Project is active.',
  'preferences.japanese_fallback': 'English fallback',
  'preferences.reduced_motion': 'Reduce Motion / Animations',
  'project.no_eligible_for_action': 'No eligible Projects are available for this action.',
  'project.deletion_submitted': 'Deletion request submitted.',
  'project.error.active_project_required_for_creation':
    'Create Project is unavailable until a Project is active.',
  'project.created': 'Project created.',
  'project.recovery_pending':
    'The previous Project change has no confirmed result yet. Check the existing result before trying again.',
  'project.lifecycle.active': 'Active',
  'project.lifecycle.archiving': 'Archiving',
  'project.lifecycle.restoring': 'Restoring',
  'project.lifecycle.delete_requested': 'Deletion requested',
  'project.lifecycle.deleting': 'Deleting',
  'project.lifecycle.deleted': 'Deleted',
  'project.lifecycle.recovery_required': 'Recovery required',
  'project.lifecycle.inactive': 'Inactive',
  'project.lifecycle.archived': 'Archived',
  'project.lifecycle.unknown': 'Unavailable lifecycle state',
  'ai.status.connected': 'Connected',
  'ai.status.authentication_failed': 'Authentication failed',
  'ai.status.model_unavailable': 'Model unavailable',
  'ai.status.rate_limited': 'Rate limited',
  'ai.status.temporarily_unavailable': 'Temporarily unavailable',
  'ai.status.connection_failed': 'Connection failed',
  'ai.privacy.review_required': 'Review required',
  'ai.privacy.approved': 'Approved',
  'ai.privacy.not_approved': 'Not approved',
  'ai.configuration_unchanged_after_credential':
    'Credential saved; AI configuration was not changed',
  'ai.configuration_not_saved': 'AI configuration was not saved',
  'ai.credential_not_repeated':
    'The saved credential was not repeated. Refresh the current settings and explicitly try the configuration again.',
  'privacy.summary': 'Privacy summary',
  'privacy.external_allowed': 'Allowed',
  'privacy.not_approved': 'Not approved',
  'privacy.approval.review_pending': 'Review pending',
  'privacy.transfer_may_permit': 'May permit private external transfer after approval.',
  'privacy.transfer_blocked': 'Currently blocks private external transfer.',
  'privacy.preconditions_load_failed': 'Current privacy review preconditions could not be loaded.',
  'privacy.owner_approval_explanation':
    'Owner approval is required before private Project context may be sent to external AI providers. Restricted context remains blocked.',
  'privacy.profile_label': 'Privacy profile:',
  'privacy.profile.local_only': 'Local only',
  'privacy.profile.restricted_external': 'Restricted external',
  'privacy.profile.controlled_external': 'Controlled external',
  'privacy.profile.custom': 'Custom',
  'privacy.sensitivity.normal': 'Normal',
  'privacy.sensitivity.sensitive': 'Sensitive',
  'privacy.sensitivity.highly_sensitive': 'Highly sensitive',
  'privacy.approval.approved': 'Approved',
  'privacy.sensitivity_label': 'Sensitivity:',
  'privacy.external_transfer_label': 'External transfer:',
  'privacy.project_approval_label': 'Project approval:',
  'privacy.deployment_label': 'Deployment:',
  'privacy.restricted_context':
    'Restricted Project context is never sent to an external AI provider.',
  'privacy.retention_label': 'Retention:',
  'privacy.loading_preconditions': 'Loading current review preconditions...',
  'privacy.approve_transfer':
    'Approve private Project context transfer when deployment policy permits it?',
  'ai.configure': 'Configure AI',
  'ai.test': 'Test AI Connection',
  'ai.load_failed': 'Failed to load AI settings.',
  'ai.loading': 'Loading AI settings...',
  'ai.provider': 'Provider',
  'ai.model': 'Model',
  'ai.api_key': 'API Key (write-only)',
  'ai.test_connection': 'Test Connection',
  'ai.testing': 'Testing...',
  'ai.save_configuration': 'Save AI configuration',
  'ai.provider_privacy': 'Provider privacy',
  'ai.error.credential_secret_unavailable': 'The credential secret is no longer available.',
  'ai.error.credential_selection_unavailable': 'The exact credential could not be selected.',
  'ai.error.draft_secret_unavailable': 'The draft secret is no longer available.',
  'ai.error.provider_required_for_privacy':
    'Select a registered provider before requesting privacy review.',
  'ai.error.no_privacy_proposal': 'No provider privacy proposal is awaiting review.',
  'ai.error.active_credential_unavailable': 'The exact active credential is no longer available.',
  'ai.credential_actions': 'Credential actions',
  'ai.configuration_saved': 'AI configuration saved.',
  'ai.configuration_ready':
    'The selected provider and model are ready for the next new AI execution.',
  'ai.credential_result_check': 'Credential result needs checking.',
  'ai.credential_write_not_repeated':
    'The credential write was not repeated. Check the result to continue safely.',
  'ai.credential_not_saved': 'Credential was not saved.',
  'ai.test_failed': 'Test Connection failed.',
  'ai.privacy_proposed': 'Provider privacy review proposed.',
  'ai.privacy_proposal_needs_owner': 'The proposal still requires a separate Owner approval.',
  'ai.privacy_saved': 'Provider privacy decision saved.',
  'ai.privacy_applies_selected': 'This decision applies only to the selected provider.',
  'ai.privacy_failed': 'Provider privacy review failed.',
  'ai.credential_action_complete': 'No other provider or credential was activated automatically.',
  'ai.credential_result_still_check': 'Credential result still needs checking.',
  'ai.credential_result_later': 'No credential write was repeated. Check the result again later.',
  'ai.historical_compatibility': 'Historical Gemini compatibility applies only to this provider.',
  'ai.approve_privacy_decision': 'Approve this provider privacy decision?',
  'ai.current_credential': 'This credential is used by the current saved configuration.',
  'ai.error.provider_proposal_validation_failed':
    'Provider privacy proposal could not be validated for the selected provider.',
  'ai.request_provider_privacy': 'Request provider privacy approval',
  'ai.approve_provider_privacy': 'Approve provider privacy decision',
  'privacy.gemini_compatibility_note': 'An existing Gemini approval applies only to Google Gemini.',
  'project.manage': 'Manage Projects',
  'project.create': 'Create Project',
  'project.rename': 'Rename Project',
  'project.restore': 'Restore Project',
  'project.archive': 'Archive Project',
  'project.delete_request': 'Request Project Deletion',
  'project.loading': 'Loading Projects…',
  'project.active': 'Active Project',
  'project.rename_action': 'Rename',
  'project.archive_action': 'Archive',
  'project.restore_action': 'Restore',
  'project.request_deletion': 'Request deletion',
  'project.creating': 'Creating…',
  'project.restoring': 'Restoring…',
  'project.submitting': 'Submitting…',
  'project.confirm_archive': 'Confirm Archive',
  'project.confirm_deletion': 'Confirm Deletion Request',
  'project.name_updated': 'Project name updated.',
  'project.archived': 'Project archived.',
  'project.restored': 'Project restored.',
  'project.rejected': 'Project change was rejected.',
  'project.not_final': 'The Project change is not final yet. Check the result again.',
  'project.check_failed': 'The Project result could not be checked. Try again.',
  'project.choose_action': 'Choose a Project action.',
  'project.create_contract_fields':
    'Only the fields required by the existing Project create contract are shown.',
  'project.select_for_command': 'Select the Project for this command.',
  'search.title': 'Search',
  'search.query': 'Search query',
  'search.scope': 'Search scope',
  'search.active_project': 'Active Project',
  'search.selected_projects': 'Selected Projects',
  'search.submit': 'Search',
  'search.searching': 'Searching...',
  'search.loading': 'Searching the selected Project scope...',
  'search.no_results': 'No results in the selected Project scope.',
  'search.active_results': 'Results from the active Project.',
  'search.cross_results': 'Results from the selected accessible Projects.',
  'search.results_label': 'Search results',
  'ask.eyebrow': 'Knowledge question',
  'ask.title': 'Ask',
  'ask.question_draft': 'Question Draft',
  'ask.draft_help': 'Your question stays here until you submit it.',
  'ask.question': 'Question',
  'ask.submit': 'Submit question',
  'ask.submitting': 'Submitting...',
  'ask.conversations': 'Conversations',
  'ask.no_conversations': 'No conversations yet.',
  'ask.answer': 'Answer',
  'ask.answer_actions': 'Answer actions',
  'ask.selected_conversation': 'Selected conversation',
  'ask.partial_answer': 'Partial answer',
  'ask.open_evidence': 'Open pinned Evidence',
  'ask.answer_status': 'Answer status',
  'ask.cancel_answer': 'Cancel answer',
  'ask.answer_export': 'Answer export',
  'ask.create_or_select_project': 'Create or select a Project before asking questions.',
  'ask.loading_workspace': 'Loading Ask workspace…',
  'ask.empty_landing_hint':
    'Select an existing conversation on the right, or start a new question in the composer below.',
  'ask.mode': 'Ask mode',
  'ask.source_context': 'Source context',
  'ask.source_selection_unavailable': 'Source selection is unavailable for this question context.',
  'ask.loading_sources': 'Loading Sources…',
  'ask.sources_load_failed': 'Sources could not be loaded.',
  'ask.source_project_mismatch': 'The Source Library Project does not match this Ask resource.',
  'ask.no_sources': 'No Sources are available for Ask in this Project.',
  'ask.pinned_version': 'Pinned version',
  'ask.version': 'Version',
  'ask.check_submission_outcome': 'Check submission outcome',
  'ask.source_selection_required': 'Select at least one Source before using selected sources.',
  'ask.action_required': 'Action required:',
  'ask.review_privacy': 'Review privacy',
  'ask.provider_eligibility_unavailable':
    'Provider eligibility could not be verified. Submission remains unavailable.',
  'ask.provider_eligibility.standing_policy_disabled':
    'Automatic AI processing is disabled for this Project.',
  'ask.provider_eligibility.standing_policy_provider_mismatch':
    'Automatic AI processing is bound to a different configured provider.',
  'ask.provider_eligibility.deployment_policy_blocked':
    'Current deployment policy does not permit sending the Project context required for this question to the configured AI provider.',
  'ask.provider_eligibility.project_approval_required':
    'Project privacy approval is required before the context for this question can be sent to the configured AI provider.',
  'ask.provider_eligibility.restricted_context_blocked':
    'Restricted Project context cannot be sent to the configured AI provider.',
  'ask.submission_unavailable': 'Question submission is not available for this conversation.',
  'ask.current_conversation': '(current conversation)',
  'ask.conversation_list': 'Conversations',
  'ask.submission_rejected': 'The question submission was rejected. The Draft was preserved.',
  'ask.submission_outcome_unknown':
    'The submission outcome is still unknown. The original request identity and Draft are preserved.',
  'ask.checking_submission_outcome': 'Checking the existing submission outcome…',
  'ask.answer_result_unknown': 'The answer result is unknown. Check again before retrying.',
  'ask.answer_result_still_unknown':
    'The answer result is still unknown. Check again without submitting a new request.',
  'ask.request_rejected': 'The request was rejected. No new request was sent.',
  'ask.request_pending':
    'The request was accepted but is not resolved. No automatic retry was started.',
  'ask.result_unavailable':
    'The request completed, but its result is not available yet. Check again without submitting a new request.',
  'ask.answer_request_recovered': 'The completed answer request and its result were recovered.',
  'ask.answer_cancel_requested': 'Answer cancellation requested.',
  'ask.answer_retry_accepted': 'Answer retry accepted with a new attempt.',
  'ask.answer_export_completed': 'Answer export completed.',
  'ask.transition_proposed': 'A draft transition was proposed. Verified knowledge was not changed.',
  'ask.source_id': 'Source ID',
  'ask.source_version_id': 'SourceVersion ID',
  'ask.failure_code': 'Failure code',
  'answer.export': 'Export answer',
  'answer.retry': 'Retry answer',
  'answer.applies_selected': 'This action applies to the selected answer.',
  'answer.retry_same': 'Retry same context',
  'answer.retry_policy': 'Retry current policy',
  'answer.propose_intake': 'Propose Intake Draft',
  'answer.propose_change': 'Propose Draft ChangeSet',
  'answer.propose_directive': 'Propose Directive',
  'sources.title': 'Sources',
  'sources.eyebrow': 'Knowledge input',
  'sources.create_project': 'Create a Project before adding Sources',
  'sources.create_project_help': 'Create a Project to organize and add Sources.',
  'sources.draft_queue': 'Draft Queue',
  'sources.draft_help':
    'Drafts stay with the project where they were created until submitted or discarded.',
  'sources.no_drafts': 'No drafts yet.',
  'sources.library': 'Source Library',
  'sources.add_source': 'Add Source',
  'sources.search': 'Search Sources',
  'sources.search_submit': 'Search',
  'sources.loading_library': 'Loading Source Library…',
  'sources.no_matching': 'No matching Sources',
  'sources.none_yet': 'No Sources yet',
  'sources.change_search': 'Change the Server search query or clear it.',
  'sources.submitted_appear': 'Submitted Sources will appear here after Server processing.',
  'sources.open': 'Open source',
  'sources.unavailable': 'This source is unavailable.',
  'sources.needs_attention': 'This source needs attention before it can be used.',
  'sources.question_access_restricted': 'Question access is restricted.',
  'sources.questions_not_ready': 'Not yet available for questions.',
  'sources.preview_unavailable': 'Preview is unavailable.',
  'sources.choose_file_again': 'Choose the file again before submission.',
  'sources.submission_failed': 'Sources submission failed.',
  'sources.duplicate_decision_failed': 'Duplicate decision failed.',
  'sources.duplicate_resolution_failed': 'Duplicate resolution failed.',
  'sources.cancellation_failed': 'Cancellation failed.',
  'sources.retry_failed': 'Retry failed.',
  'sources.project_mismatch':
    'The active Project changed. These drafts remain isolated to their original Project and cannot be submitted from the current context.',
  'sources.invalid_draft': 'This draft could not be opened. Review it and try again.',
  'sources.draft_message.seeded_text_review':
    'Seeded Direct Text must be reviewed before submission.',
  'sources.draft_message.seeded_text_too_large':
    'Seeded Direct Text exceeds the active one MiB boundary.',
  'sources.draft_message.seeded_url_validation':
    'The Server will repeat URL safety validation on submission.',
  'sources.draft_message.seed_file_reselect':
    'Choose the file again. A seed cannot supply browser file bytes.',
  'sources.draft_message.direct_text_empty': 'Direct Text cannot be empty.',
  'sources.draft_message.direct_text_too_large': 'Direct Text exceeds the active one MiB limit.',
  'sources.draft_message.client_preflight':
    'Client preflight passed. The Server will validate again.',
  'sources.draft_message.file_unsupported':
    'Only text/plain and text/markdown are active in this Section.',
  'sources.draft_message.file_size': 'The file must be between 1 byte and one MiB.',
  'sources.draft_message.file_preflight':
    'Client preflight passed. The Server will verify bytes, type and filename.',
  'sources.draft_message.url_accepted':
    'Descriptor accepted locally. The Server will perform acquisition and SSRF validation.',
  'sources.draft_message.url_invalid': 'Enter an absolute HTTP(S) URL.',
  'sources.adding_draft': 'Adding draft…',
  'sources.submitting_drafts': 'Submitting drafts…',
  'sources.input_type': 'Input type',
  'sources.label': 'Label',
  'sources.classification': 'Source classification',
  'sources.classification_help':
    'This is a classification request for this new Source. The Server validates and stores the final classification; it does not change your access clearance.',
  'sources.add_intake_draft': 'Add intake draft',
  'sources.intake_drafts': 'Intake drafts',
  'sources.requested_classification': 'Requested classification:',
  'sources.remove': 'Remove',
  'sources.discard_all': 'Discard all drafts',
  'sources.submit_drafts': 'Submit drafts',
  'sources.submission': 'Submission',
  'sources.submission_id': 'Submission ID',
  'sources.submission_items': 'Submission items',
  'sources.review_duplicate': 'Review duplicate',
  'sources.retry_same': 'Retry same context',
  'sources.retry_policy': 'Retry current policy',
  'sources.cancel_submission': 'Cancel submission',
  'sources.exact_duplicate_decision': 'Exact duplicate decision',
  'sources.existing_source': 'Existing Source:',
  'sources.version': 'Version',
  'sources.offline_cached':
    'Offline. A previously authorized cached Library may be shown, but Server search and intake actions are blocked.',
  'sources.library_stale': 'This Library snapshot is stale.',
  'sources.list': 'Sources',
  'source_detail.eyebrow': 'Source detail',
  'source_detail.views': 'Source detail views',
  'source_detail.loading': 'Loading Source…',
  'source_detail.back': 'Back to Source Library',
  'source_detail.return_citation': 'Return to cited resource',
  'source_detail.return_knowledge': 'Return to Knowledge resource',
  'source_detail.version': 'Version',
  'source_detail.selected': 'Selected',
  'source_detail.preview': 'Preview',
  'source_detail.questions': 'Questions',
  'source_detail.original_preview': 'Original Preview',
  'source_detail.loading_preview': 'Loading Preview…',
  'source_detail.preview_unsupported':
    'Original bytes are available, but inline Preview is not supported for this media type.',
  'source_detail.evidence': 'Evidence',
  'source_detail.loading_evidence': 'Loading Evidence…',
  'source_detail.no_evidence': 'No Evidence is indexed yet.',
  'source_detail.version_history': 'Version history',
  'source_detail.loading_history': 'Loading Version history…',
  'source_detail.evidence_id': 'Evidence ID',
  'source_detail.evidence_revision': 'Evidence revision',
  'source_detail.source_id': 'Source ID',
  'source_detail.source_version_id': 'SourceVersion ID',
  'discovery.eyebrow': 'Knowledge discovery',
  'discovery.title': 'Discovery Inbox',
  'discovery.intro': 'Review server-found signals before they enter governed knowledge workflows.',
  'discovery.open_inbox': 'Open Discovery Inbox',
  'discovery.back_to_knowledge': 'Back to Knowledge Workspace',
  'discovery.filter_heading': 'Filter findings',
  'discovery.type_filter': 'Finding type',
  'discovery.lifecycle_filter': 'Lifecycle',
  'discovery.all_types': 'All finding types',
  'discovery.all_lifecycles': 'All lifecycle states',
  'discovery.apply_filters': 'Apply filters',
  'discovery.loading': 'Loading Discovery Inbox…',
  'discovery.loading_more': 'Loading more findings…',
  'discovery.load_more': 'Load more findings',
  'discovery.empty_title': 'No Discovery findings',
  'discovery.empty_description': 'The server returned no readable findings for this Project.',
  'discovery.list_failure': 'Discovery findings could not be loaded.',
  'discovery.detail_loading': 'Loading Discovery finding…',
  'discovery.detail_failure': 'This Discovery finding could not be loaded.',
  'discovery.not_found_title': 'Discovery finding unavailable',
  'discovery.not_found_description':
    'This exact finding revision is not available in the current Project scope.',
  'discovery.non_canonical': 'Derived finding · not Canonical',
  'discovery.review_ready': 'Review-ready',
  'discovery.open_review': 'Open in Review',
  'discovery.open_graph': 'Open in Graph',
  'discovery.authority': 'Authority',
  'discovery.finding_type': 'Finding type',
  'discovery.lifecycle': 'Lifecycle',
  'discovery.generation': 'Generation',
  'discovery.summary': 'Summary',
  'discovery.rationale': 'Why this was found',
  'discovery.derivation': 'How it was derived',
  'discovery.governance': 'Governance state',
  'discovery.reentry': 'Validation re-entry',
  'discovery.validation': 'Validation',
  'discovery.review_readiness': 'Review readiness',
  'discovery.freshness': 'Freshness',
  'discovery.payload': 'Finding context',
  'discovery.related_resources': 'Related resources',
  'discovery.evidence': 'Evidence and Source lineage',
  'discovery.open_source_evidence': 'Open source evidence',
  'discovery.open_related_resource': 'Open related resource',
  'discovery.no_lineage': 'No accessible lineage is available for this finding.',
  'discovery.resource': 'Related knowledge resource',
  'discovery.context': 'Context',
  'discovery.subject': 'Subject',
  'discovery.missing_information': 'Missing information',
  'discovery.question': 'Question',
  'discovery.coverage_gap': 'Coverage gap',
  'discovery.required_evidence': 'Required evidence',
  'discovery.source_endpoint': 'Source',
  'discovery.target_endpoint': 'Target',
  'discovery.proposed_relation': 'Proposed relationship',
  'discovery.direction': 'Direction',
  'discovery.direction.directed': 'Directed',
  'discovery.direction.undirected': 'Undirected',
  'discovery.pattern': 'Pattern',
  'discovery.members': 'Related members',
  'discovery.contradiction': 'Possible contradiction',
  'discovery.investigation_next_step': 'Suggested next step',
  'discovery.suggested_action': 'Suggested action',
  'discovery.execution_status': 'Execution status',
  'discovery.candidate_only': 'Candidate only · no execution is available',
  'discovery.risk_context': 'Risk context',
  'discovery.no_review_action': 'Review is not available for this lifecycle state.',
  'discovery.dismiss': 'Dismiss finding',
  'discovery.dismissed': 'This derived finding was dismissed by the Project owner.',
  'discovery.dismiss_failed': 'The Discovery finding could not be dismissed.',
  'discovery.dismiss_outcome_unknown':
    'The dismiss result is uncertain. Resolve the existing command before retrying.',
  'discovery.dismiss_not_available': 'Dismissal is unavailable for this lifecycle state.',
  'discovery.freshness_current': 'Current under the server-provided Discovery projection.',
  'discovery.freshness_revalidation':
    'The server requires revalidation before relying on this finding.',
  'discovery.freshness_unknown': 'Freshness is unavailable from the server.',
  'discovery.feedback.useful': 'Useful',
  'discovery.feedback.not_relevant': 'Not relevant',
  'discovery.feedback.heading': 'Feedback',
  'discovery.feedback.help':
    'Tell Shotgun how this discovery worked for you. Feedback does not change Canonical knowledge.',
  'discovery.feedback.useful_title': 'Mark as useful',
  'discovery.feedback.not_relevant_title': 'Mark as not relevant',
  'discovery.feedback.already_known': 'Already known',
  'discovery.feedback.too_frequent': 'Too frequent',
  'discovery.feedback.too_frequent_description': 'Record that this discovery is shown too often.',
  'discovery.feedback.snooze': 'Snooze discovery',
  'discovery.feedback.suppress_exact': 'Hide this discovery',
  'discovery.feedback.suppress_similar': 'Hide similar discoveries',
  'discovery.feedback.report_issue': 'Report an issue',
  'discovery.feedback.history_title': 'Feedback history',
  'discovery.feedback.utility_description':
    'Record how this discovery worked for you without changing Canonical knowledge.',
  'discovery.feedback.snooze_description':
    'Temporarily defer this discovery without deleting its history or changing Canonical knowledge.',
  'discovery.feedback.snooze_finding_only': 'Snooze applies to this discovery only.',
  'discovery.feedback.suppression_description':
    'Hide the selected scope from Discovery presentation. This does not delete the Finding or change Canonical knowledge.',
  'discovery.feedback.report_issue_description':
    'Ask Shotgun to re-check this discovery. It does not immediately change Canonical knowledge.',
  'discovery.feedback.history_description':
    'Review owner feedback recorded for this exact discovery revision.',
  'discovery.feedback.utility_boundary':
    'This records usefulness for ordering and timing only. It does not change Canonical knowledge.',
  'discovery.feedback.report_boundary':
    'This asks Shotgun to re-check the discovery. It does not immediately change Canonical knowledge or approve or reject Review.',
  'conflict_rules.title': 'Typed proposition conflict rules',
  'conflict_rules.description':
    'These rules tell Shotgun which typed relations may be possible conflicts when they describe the same exact pair.',
  'conflict_rules.safety':
    'A rule does not make a relation false or create a Fact or Canonical knowledge by itself.',
  'conflict_rules.list_label': 'Conflict rules',
  'conflict_rules.empty': 'No conflict rules are configured for this Project.',
  'conflict_rules.project_required': 'Select an active Project first.',
  'conflict_rules.edit_title': 'Edit conflict rule',
  'conflict_rules.add_title': 'Add conflict rule',
  'conflict_rules.relation_a': 'Relation type A',
  'conflict_rules.relation_b': 'Relation type B',
  'conflict_rules.direction': 'Direction',
  'conflict_rules.directed': 'Same directed relationship',
  'conflict_rules.undirected': 'Undirected relationship',
  'conflict_rules.confirm_title': 'Confirm conflict rule change',
  'conflict_rules.confirmation':
    'Shotgun will flag future matching relation pairs as possible conflicts. The rule does not change Canonical knowledge by itself.',
  'conflict_rules.check_outcome': 'Check existing result',
  'conflict_rules.status_active': 'Active',
  'conflict_rules.status_retired': 'Retired',
  'conflict_rules.status_superseded': 'Superseded',
  'discovery.feedback.scope': 'Apply to',
  'discovery.feedback.scope_finding': 'This discovery only',
  'discovery.feedback.scope_project': 'This Project',
  'discovery.feedback.snooze_until': 'Snooze for',
  'discovery.feedback.snooze_one_hour': 'One hour',
  'discovery.feedback.snooze_one_day': 'One day',
  'discovery.feedback.snooze_one_week': 'One week',
  'discovery.feedback.issue_kind': 'What should Shotgun re-check?',
  'discovery.feedback.issue.incorrect_relation': 'The relationship is incorrect',
  'discovery.feedback.issue.incorrect_relation_description':
    'The proposed relationship between resources does not match the available context.',
  'discovery.feedback.issue.insufficient_evidence': 'The evidence is insufficient',
  'discovery.feedback.issue.insufficient_evidence_description':
    'The discovery needs stronger or more complete supporting evidence.',
  'discovery.feedback.issue.wrong_entity': 'The entity is wrong',
  'discovery.feedback.issue.wrong_entity_description':
    'The discovery appears to refer to a different person, place, thing, or record.',
  'discovery.feedback.issue.temporal_error': 'The timing is wrong',
  'discovery.feedback.issue.temporal_error_description':
    'The discovery appears to place an event or state in the wrong time period.',
  'discovery.feedback.issue.misleading_pattern': 'The pattern is misleading',
  'discovery.feedback.issue.misleading_pattern_description':
    'The reported pattern does not represent the available information well.',
  'discovery.feedback.issue.misidentified_conflict': 'The conflict is misidentified',
  'discovery.feedback.issue.misidentified_conflict_description':
    'The discovery appears to describe a conflict that is not actually present.',
  'discovery.feedback.reason_optional': 'Optional note',
  'discovery.feedback.reason_count': 'Characters:',
  'discovery.feedback.submit': 'Record feedback',
  'discovery.feedback.hide_confirm': 'Confirm hiding',
  'discovery.feedback.snooze_confirm': 'Confirm snooze',
  'discovery.feedback.report_submit': 'Request re-check',
  'discovery.feedback.recorded': 'Feedback recorded.',
  'discovery.feedback.recheck_requested':
    'Re-check requested. This does not mean the discovery was corrected.',
  'discovery.feedback.failed':
    'Feedback could not be recorded. The discovery may no longer be available in this Project.',
  'discovery.feedback.outcome_unknown':
    'The result is uncertain. Check the existing command result before trying again.',
  'discovery.feedback.check_result': 'Check result',
  'discovery.feedback.history_recorded': 'Feedback recorded',
  'discovery.feedback.history_recheck_requested': 'Re-check requested',
  'discovery.feedback.history_active': 'Active',
  'discovery.feedback.history_expired': 'Expired',
  'discovery.feedback.history_until': 'until',
  'discovery.feedback.history_scope': 'Scope',
  'discovery.feedback.history_effect': 'Current effect',
  'discovery.feedback.history_reason': 'Note',
  'discovery.feedback.history_empty': 'No owner feedback is recorded for this revision.',
  'discovery.feedback.history_loading': 'Loading feedback history…',
  'discovery.feedback.history_unavailable': 'Feedback history is not available for this discovery.',
  'discovery.mandatory_visibility': 'Shown because this discovery still requires attention.',
  'discovery.open_activity': 'View execution activity',
  'discovery.type.knowledge_gap': 'Knowledge gap',
  'discovery.type.evidence_gap': 'Evidence gap',
  'discovery.type.relation_hypothesis': 'Relationship hypothesis',
  'discovery.type.pattern_hypothesis': 'Pattern hypothesis',
  'discovery.type.conflict_hypothesis': 'Conflict hypothesis',
  'discovery.type.clarification_question': 'Clarification question',
  'discovery.type.action_suggestion': 'Action suggestion',
  'discovery.lifecycle.new': 'New',
  'discovery.lifecycle.validating': 'Validating',
  'discovery.lifecycle.review_ready': 'Ready for Review',
  'discovery.lifecycle.reentered': 'Validation re-entered',
  'discovery.lifecycle.dismissed': 'Dismissed',
  'discovery.lifecycle.suppressed': 'Suppressed',
  'discovery.lifecycle.resolved': 'Resolved',
  'discovery.lifecycle.stale': 'Stale',
  'discovery.lifecycle.superseded': 'Superseded',
  'discovery.generation.deterministic': 'Rule-based',
  'discovery.generation.ai_assisted': 'AI-assisted',
  'discovery.generation.hybrid': 'Rule-based and AI-assisted',
  'discovery.reentry.not_requested': 'Not requested',
  'discovery.reentry.processed': 'Processed',
  'discovery.reentry.ineligible': 'Not eligible',
  'discovery.reentry.blocked_non_retryable': 'Blocked; cannot retry',
  'discovery.reentry.retryable': 'Retry available',
  'discovery.validation.not_started': 'Not started',
  'discovery.validation.validating': 'Validating',
  'discovery.validation.validated': 'Validated',
  'discovery.validation.unknown': 'Unknown',
  'discovery.review_readiness.not_eligible': 'Not eligible',
  'discovery.review_readiness.eligible': 'Eligible after validation',
  'discovery.freshness.current': 'Current',
  'discovery.freshness.revalidation_required': 'Revalidation required',
  'discovery.freshness.unknown': 'Unknown',
  'discovery.resource.canonical_claim': 'Canonical claim',
  'discovery.resource.canonical_entity': 'Canonical entity',
  'discovery.resource.canonical_event': 'Canonical event',
  'discovery.resource.canonical_relation': 'Canonical relationship',
  'discovery.resource.canonical_conflict': 'Canonical conflict',
  'discovery.resource.canonical_decision': 'Canonical decision',
  'discovery.resource.source': 'Source',
  'discovery.resource.source_version': 'Source version',
  'discovery.resource.compiled_truth_item': 'Compiled Truth item',
  'enum.ask_mode.canonical_only': 'Verified knowledge only',
  'enum.ask_mode.source_exploration': 'Use selected sources',
  'enum.ask_mode.hybrid': 'Verified knowledge + selected sources',
  'enum.ask_mode.unknown': 'Ask with the selected context',
  'enum.source_preview.not_ready': 'Preview not ready',
  'enum.source_preview.processing': 'Preparing preview',
  'enum.source_preview.ready': 'Preview ready',
  'enum.source_preview.failed': 'Preview unavailable',
  'enum.source_preview.access_restricted': 'Preview access restricted',
  'enum.source_preview.unknown': 'Preview status unavailable',
  'enum.source_ask.not_ready': 'Not yet available for questions',
  'enum.source_ask.source_version_ready': 'Available for questions',
  'enum.source_ask.evidence_ready': 'Available with indexed evidence',
  'enum.source_ask.action_required': 'Needs attention before use',
  'enum.source_ask.failed': 'Unavailable for questions',
  'enum.source_ask.access_restricted': 'Question access restricted',
  'enum.source_ask.unknown': 'Question availability unknown',
  'enum.intake_state.validating': 'Checking',
  'enum.intake_state.queued': 'Queued',
  'enum.intake_state.running': 'Processing',
  'enum.intake_state.partial': 'Partially completed',
  'enum.intake_state.action_required': 'Needs attention',
  'enum.intake_state.succeeded': 'Completed',
  'enum.intake_state.failed': 'Failed',
  'enum.intake_state.cancel_requested': 'Cancellation requested',
  'enum.intake_state.cancelled': 'Cancelled',
  'enum.intake_state.outcome_indeterminate': 'Checking final outcome',
  'enum.intake_state.unknown': 'Status unavailable',
  'enum.intake_kind.direct_text': 'Direct Text',
  'enum.intake_kind.file': 'File',
  'enum.intake_kind.url': 'URL',
  'enum.intake_kind.unknown': 'Source',
  'enum.intake_validation.ready': 'Ready to submit',
  'enum.intake_validation.unsupported_format': 'Unsupported format',
  'enum.intake_validation.encrypted': 'Encrypted content',
  'enum.intake_validation.corrupt': 'Unreadable content',
  'enum.intake_validation.inaccessible': 'Cannot be accessed',
  'enum.intake_validation.policy_blocked': 'Blocked by policy',
  'enum.intake_validation.too_large': 'File is too large',
  'enum.intake_validation.invalid_filename': 'Invalid file name',
  'enum.intake_validation.invalid_url': 'Invalid URL',
  'enum.intake_validation.unsafe_destination': 'Unsafe destination',
  'enum.intake_validation.unknown': 'Check required',
  'enum.duplicate.reuse': 'Use the existing version',
  'enum.duplicate.version_candidate': 'Create a new version candidate',
  'enum.duplicate.separate_source': 'Create a separate source',
  'enum.duplicate.cancel': 'Cancel this submission',
  'enum.duplicate.unknown': 'Resolve duplicate',
  'enum.answer_run.queued': 'Queued',
  'enum.answer_run.running': 'Answering',
  'enum.answer_run.action_required': 'Needs attention',
  'enum.answer_run.succeeded': 'Completed',
  'enum.answer_run.failed': 'Failed',
  'enum.answer_run.cancel_requested': 'Cancellation requested',
  'enum.answer_run.cancelled': 'Cancelled',
  'enum.answer_run.outcome_unknown': 'Checking final outcome',
  'enum.answer_run.unknown': 'Answer status unavailable',
  'enum.transformation.not_started': 'Not processed yet',
  'enum.transformation.running': 'Processing',
  'enum.transformation.ready': 'Ready',
  'enum.transformation.failed': 'Processing failed',
  'enum.transformation.unknown': 'Processing status unavailable',
  'enum.evidence_origin.original': 'Original source',
  'enum.evidence_origin.translation': 'Translation',
  'enum.evidence_origin.summary': 'Summary',
  'enum.evidence_origin.annotation': 'Annotation',
  'enum.evidence_origin.ai_output': 'AI output',
  'enum.evidence_origin.unknown': 'Source evidence',
  'enum.media_type.text': 'Text',
  'enum.media_type.markdown': 'Markdown',
  'enum.media_type.pdf': 'PDF',
  'enum.media_type.web': 'Web page',
  'enum.media_type.image': 'Image',
  'enum.media_type.document': 'Document',
  'enum.sensitivity.public': 'Public',
  'enum.sensitivity.internal': 'Internal',
  'enum.sensitivity.private': 'Private',
  'enum.sensitivity.unknown': 'Unclassified',
} as const;

export type ProductMessageKey = keyof typeof enUS;

const koKR: Record<ProductMessageKey, string> = {
  'common.close': '닫기',
  'common.save': '저장',
  'common.cancel': '취소',
  'common.saving': '저장 중...',
  'common.checking': '확인 중...',
  'common.check_result': '결과 확인',
  'common.loading': '불러오는 중...',
  'common.edit': '편집',
  'common.retire': '폐기',
  'common.confirm': '확인',
  'common.add': '추가',
  'common.loading_preferences': '환경설정을 불러오는 중...',
  'shell.current_project': '현재 프로젝트',
  'shell.not_created': '생성되지 않음',
  'shell.primary_navigation': '주 탐색',
  'shell.mobile_navigation': '모바일 탐색',
  'shell.offline':
    '오프라인입니다. 캐시 정보가 오래되었을 수 있으며 서버 작업과 검색은 사용할 수 없습니다.',
  'shell.additional_states': '추가 상태',
  'nav.home': '홈',
  'nav.sources': '소스',
  'nav.ask': '질문',
  'nav.available': '사용 가능',
  'nav.coming_later': '추후 제공',
  'nav.temporarily_unavailable': '일시적으로 사용할 수 없음',
  'nav.access_restricted': '접근 제한',
  'home.first_run': '첫 실행',
  'home.create_first_project': '첫 프로젝트를 만드세요',
  'home.create_first_project_help': '시작하려면 첫 프로젝트를 만드세요.',
  'home.open_onboarding': '프로젝트 시작 설정 열기',
  'home.action_center': '작업 센터',
  'home.primary_actions': '주요 작업',
  'home.attention': '확인 필요',
  'home.continue_working': '계속 작업',
  'home.recent_and_pinned': '최근 및 고정',
  'home.loading': '홈 작업 센터를 불러오는 중…',
  'home.stale': '이 서버 스냅샷은 오래되었습니다. 새로 고칠 때까지 작업을 사용할 수 없습니다.',
  'home.server_resources': '서버 리소스',
  'home.browser_drafts': '브라우저 초안',
  'home.browser_draft_never_ranked': '브라우저 초안 · 서버 순위에 반영되지 않음',
  'home.recent': '최근',
  'home.pinned': '고정',
  'commands.keyboard_hint': '↑↓ 탐색 · Enter 선택 · Esc 닫기',
  'global.switch.resolve_workspace': '프로젝트를 전환하기 전에 현재 작업 공간을 정리하세요.',
  'global.switch.unknown_not_retried':
    '알 수 없는 명령은 프로젝트 전환 중에 다시 시도하지 않습니다.',
  'search.result_count': '검색 결과 {count}개',
  'commands.title': '명령',
  'commands.help': '이름, 별칭 또는 키워드로 명령을 찾으세요.',
  'commands.search_label': '명령 검색',
  'commands.no_match': '일치하는 명령이 없습니다.',
  'commands.category.help': '도움말',
  'commands.category.search': '검색',
  'commands.category.project': '프로젝트',
  'commands.category.answer': '답변',
  'commands.category.ai': 'AI',
  'commands.category.privacy': '개인정보',
  'commands.category.preferences': '환경설정',
  'commands.category.navigation': '탐색',
  'commands.category.inspection': '점검',
  'preferences.locale_title': '언어 환경설정',
  'preferences.timezone_title': '시간대 환경설정',
  'preferences.display_title': '화면 환경설정',
  'preferences.locale': '언어',
  'preferences.updated': '환경설정을 업데이트했습니다.',
  'preferences.rejected': '환경설정 변경이 거부되었습니다.',
  'preferences.not_final': '환경설정 변경이 아직 완료되지 않았습니다. 결과를 다시 확인하세요.',
  'preferences.check_failed': '환경설정 결과를 확인하지 못했습니다. 다시 시도하세요.',
  'preferences.timezone': '시간대',
  'preferences.date_format': '날짜 및 시간 형식',
  'preferences.screen_density': '화면 밀도',
  'technical.title': '기술 정보',
  'privacy.review_title': '개인정보 검토',
  'privacy.project_title': '프로젝트 개인정보',
  'privacy.loading': '개인정보 설정을 불러오는 중...',
  'privacy.open_review': '개인정보 검토 열기',
  'privacy.request_review': '외부 AI 전송 검토 요청',
  'privacy.approve_review': '검토된 개인정보 제안 승인',
  'privacy.owner_approval_required': '이 개인정보 검토에는 아직 소유자 승인이 필요합니다.',
  'privacy.project_approval_recorded':
    '프로젝트 개인정보 승인을 기록했습니다. 배포 정책은 계속 적용됩니다.',
  'privacy.review_not_final': '개인정보 검토가 아직 완료되지 않았습니다. 결과를 다시 확인하세요.',
  'privacy.review_needs_checking': '개인정보 검토 결과를 확인해야 합니다. 다시 제출하지 않습니다.',
  'privacy.review_completed': '개인정보 검토를 완료했습니다.',
  'privacy.review_rejected': '개인정보 검토가 거부되었습니다.',
  'privacy.review_check_failed': '개인정보 검토 결과를 확인하지 못했습니다. 다시 시도하세요.',
  'privacy.load_failed': '개인정보 설정을 불러오지 못했습니다.',
  'commands.unavailable.answer_offline': '오프라인 상태에서는 답변 작업을 사용할 수 없습니다.',
  'commands.unavailable.ai_configuration_offline':
    '오프라인 상태에서는 AI 구성을 사용할 수 없습니다.',
  'commands.unavailable.ai_test_offline':
    '오프라인 상태에서는 AI 연결 테스트를 사용할 수 없습니다.',
  'commands.unavailable.privacy_open_offline': '오프라인 상태에서는 개인정보를 사용할 수 없습니다.',
  'commands.unavailable.privacy_review_offline':
    '오프라인 상태에서는 개인정보 검토를 사용할 수 없습니다.',
  'commands.unavailable.answer_pending':
    '다른 작업을 시작하기 전에 현재 답변 요청 결과를 확인하세요.',
  'commands.unavailable.search_offline': '오프라인 상태에서는 검색을 사용할 수 없습니다.',
  'commands.unavailable.project_offline': '오프라인 상태에서는 프로젝트 제어를 사용할 수 없습니다.',
  'commands.unavailable.preferences_offline': '오프라인 상태에서는 환경설정을 사용할 수 없습니다.',
  'commands.unavailable.preferences_project_required':
    '프로젝트가 활성화될 때까지 환경설정을 사용할 수 없습니다.',
  'commands.unavailable.project_switch_offline':
    '오프라인 상태에서는 프로젝트 전환을 사용할 수 없습니다.',
  'commands.unavailable.discovery_offline':
    '오프라인 상태에서는 발견 항목 소유자 작업을 사용할 수 없습니다.',
  'commands.unavailable.discovery_pending': '발견 항목 작업이 아직 처리 중입니다.',
  'commands.unavailable.conflict_rules_offline': '오프라인에서는 충돌 규칙을 사용할 수 없습니다.',
  'preferences.japanese_fallback': '영어 기본값',
  'preferences.reduced_motion': '동작 줄이기 / 애니메이션',
  'project.error.active_project_required_for_creation':
    '활성 프로젝트가 있어야 프로젝트를 생첱할 수 있습니다.',
  'project.no_eligible_for_action': '이 작업에 사용할 수 있는 프로젝트가 없습니다.',
  'project.deletion_submitted': '삭제 요청이 제출되었습니다.',
  'project.created': '프로젝트가 생성되었습니다.',
  'project.recovery_pending':
    '이전 프로젝트 변경의 확인된 결과가 아직 없습니다. 다시 시도하기 전에 기존 결과를 확인하세요.',
  'project.lifecycle.active': '활성',
  'project.lifecycle.archiving': '보관 중',
  'project.lifecycle.restoring': '복원 중',
  'project.lifecycle.delete_requested': '삭제 요청됨',
  'project.lifecycle.deleting': '삭제 중',
  'project.lifecycle.deleted': '삭제됨',
  'project.lifecycle.recovery_required': '복구 필요',
  'project.lifecycle.inactive': '비활성',
  'project.lifecycle.archived': '보관됨',
  'project.lifecycle.unknown': '확인할 수 없는 수명 주기 상태',
  'ai.status.connected': '연결됨',
  'ai.status.authentication_failed': '인증 실패',
  'ai.status.model_unavailable': '모델을 사용할 수 없음',
  'ai.status.rate_limited': '요청 한도 초과',
  'ai.status.temporarily_unavailable': '일시적으로 사용할 수 없음',
  'ai.status.connection_failed': '연결 실패',
  'ai.privacy.review_required': '검토 필요',
  'ai.privacy.approved': '승인됨',
  'ai.privacy.not_approved': '승인되지 않음',
  'ai.configuration_unchanged_after_credential':
    '자격 증명은 저장되었지만 AI 구성은 변경되지 않았습니다',
  'ai.configuration_not_saved': 'AI 구성이 저장되지 않았습니다',
  'ai.credential_not_repeated':
    '저장된 자격 증명을 다시 사용하지 않았습니다. 현재 설정을 새로 고친 후 구성을 명시적으로 다시 시도하세요.',
  'privacy.summary': '개인정보 요약',
  'privacy.external_allowed': '허용됨',
  'privacy.not_approved': '승인되지 않음',
  'privacy.approval.review_pending': '검토 대기 중',
  'privacy.transfer_may_permit': '승인 후 비공개 외부 전송을 허용할 수 있습니다.',
  'privacy.transfer_blocked': '현재 비공개 외부 전송을 차단합니다.',
  'privacy.preconditions_load_failed': '현재 개인정보 검토 사전 조건을 불러오지 못했습니다.',
  'privacy.owner_approval_explanation':
    '비공개 프로젝트 컨텍스트를 외부 AI 제공자에게 전송하려면 소유자 승인이 필요합니다. 제한된 컨텍스트는 계속 차단됩니다.',
  'privacy.profile_label': '개인정보 프로필:',
  'privacy.profile.local_only': '로컬 전용',
  'privacy.profile.restricted_external': '제한된 외부',
  'privacy.profile.controlled_external': '제어된 외부',
  'privacy.profile.custom': '사용자 지정',
  'privacy.sensitivity.normal': '일반',
  'privacy.sensitivity.sensitive': '민감',
  'privacy.sensitivity.highly_sensitive': '매우 민감',
  'privacy.approval.approved': '승인됨',
  'privacy.sensitivity_label': '민감도:',
  'privacy.external_transfer_label': '외부 전송:',
  'privacy.project_approval_label': '프로젝트 승인:',
  'privacy.deployment_label': '배포:',
  'privacy.restricted_context': '제한된 프로젝트 컨텍스트는 외부 AI 제공자에게 전송되지 않습니다.',
  'privacy.retention_label': '보존:',
  'privacy.loading_preconditions': '현재 검토 사전 조건을 불러오는 중...',
  'privacy.approve_transfer': '배포 정책이 허용할 때 비공개 프로젝트 컨텍스트 전송을 승인할까요?',
  'ai.configure': 'AI 구성',
  'ai.test': 'AI 연결 테스트',
  'ai.load_failed': 'AI 설정을 불러오지 못했습니다.',
  'ai.loading': 'AI 설정을 불러오는 중...',
  'ai.provider': '제공자',
  'ai.model': '모델',
  'ai.api_key': 'API 키 (쓰기 전용)',
  'ai.test_connection': '연결 테스트',
  'ai.testing': '테스트 중...',
  'ai.save_configuration': 'AI 구성 저장',
  'ai.provider_privacy': '제공자 개인정보',
  'ai.error.credential_secret_unavailable': '자격 증명 비밀 값을 더 이상 사용할 수 없습니다.',
  'ai.error.credential_selection_unavailable': '정확한 자격 증명을 선택할 수 없습니다.',
  'ai.error.draft_secret_unavailable': '임시 비밀 값을 더 이상 사용할 수 없습니다.',
  'ai.error.provider_required_for_privacy':
    '개인정보 검토를 요청하려면 등록된 제공자를 선택하세요.',
  'ai.error.no_privacy_proposal': '검토 대기 중인 제공자 개인정보 제안이 없습니다.',
  'ai.error.active_credential_unavailable': '정확한 활성 자격 증명을 더 이상 사용할 수 없습니다.',
  'ai.credential_actions': '자격 증명 작업',
  'ai.configuration_saved': 'AI 구성을 저장했습니다.',
  'ai.configuration_ready': '선택한 제공자와 모델이 다음 새 AI 실행에 사용할 준비가 되었습니다.',
  'ai.credential_result_check': '자격 증명 결과를 확인해야 합니다.',
  'ai.credential_write_not_repeated':
    '자격 증명 쓰기를 반복하지 않았습니다. 계속하려면 결과를 확인하세요.',
  'ai.credential_not_saved': '자격 증명을 저장하지 못했습니다.',
  'ai.test_failed': '연결 테스트에 실패했습니다.',
  'ai.privacy_proposed': '제공자 개인정보 검토를 제안했습니다.',
  'ai.privacy_proposal_needs_owner': '이 제안에는 별도의 소유자 승인이 필요합니다.',
  'ai.privacy_saved': '제공자 개인정보 결정을 저장했습니다.',
  'ai.privacy_applies_selected': '이 결정은 선택한 제공자에만 적용됩니다.',
  'ai.privacy_failed': '제공자 개인정보 검토에 실패했습니다.',
  'ai.credential_action_complete': '다른 제공자나 자격 증명을 자동으로 활성화하지 않았습니다.',
  'ai.credential_result_still_check': '자격 증명 결과를 계속 확인해야 합니다.',
  'ai.credential_result_later':
    '자격 증명 쓰기를 반복하지 않았습니다. 나중에 결과를 다시 확인하세요.',
  'ai.historical_compatibility': '이전 Gemini 호환성은 이 제공자에만 적용됩니다.',
  'ai.approve_privacy_decision': '이 제공자의 개인정보 결정을 승인할까요?',
  'ai.current_credential': '이 자격 증명은 현재 저장된 구성에서 사용됩니다.',
  'ai.error.provider_proposal_validation_failed':
    '선택한 제공자의 제공자 개인정보 제안을 확인할 수 없습니다.',
  'ai.request_provider_privacy': '제공자 개인정보 승인 요청',
  'ai.approve_provider_privacy': '제공자 개인정보 결정 승인',
  'privacy.gemini_compatibility_note': '기존 Gemini 승인은 Google Gemini에만 적용됩니다.',
  'project.manage': '프로젝트 관리',
  'project.create': '프로젝트 만들기',
  'project.rename': '프로젝트 이름 바꾸기',
  'project.restore': '프로젝트 복원',
  'project.archive': '프로젝트 보관',
  'project.delete_request': '프로젝트 삭제 요청',
  'project.loading': '프로젝트를 불러오는 중…',
  'project.active': '현재 프로젝트',
  'project.rename_action': '이름 바꾸기',
  'project.archive_action': '보관',
  'project.restore_action': '복원',
  'project.request_deletion': '삭제 요청',
  'project.creating': '생성 중…',
  'project.restoring': '복원 중…',
  'project.submitting': '제출 중…',
  'project.confirm_archive': '보관 확인',
  'project.confirm_deletion': '삭제 요청 확인',
  'project.name_updated': '프로젝트 이름을 변경했습니다.',
  'project.archived': '프로젝트를 보관했습니다.',
  'project.restored': '프로젝트를 복원했습니다.',
  'project.rejected': '프로젝트 변경이 거부되었습니다.',
  'project.not_final': '프로젝트 변경이 아직 완료되지 않았습니다. 결과를 다시 확인하세요.',
  'project.check_failed': '프로젝트 결과를 확인하지 못했습니다. 다시 시도하세요.',
  'project.choose_action': '프로젝트 작업을 선택하세요.',
  'project.create_contract_fields': '기존 프로젝트 생성 계약에 필요한 필드만 표시됩니다.',
  'project.select_for_command': '이 명령에 사용할 프로젝트를 선택하세요.',
  'search.title': '검색',
  'search.query': '검색어',
  'search.scope': '검색 범위',
  'search.active_project': '현재 프로젝트',
  'search.selected_projects': '선택한 프로젝트',
  'search.submit': '검색',
  'search.searching': '검색 중...',
  'search.loading': '선택한 프로젝트 범위에서 검색 중...',
  'search.no_results': '선택한 프로젝트 범위에 결과가 없습니다.',
  'search.active_results': '현재 프로젝트의 결과입니다.',
  'search.cross_results': '선택한 접근 가능 프로젝트의 결과입니다.',
  'search.results_label': '검색 결과',
  'ask.eyebrow': '지식 질문',
  'ask.title': '질문',
  'ask.question_draft': '질문 초안',
  'ask.draft_help': '제출하기 전까지 질문은 여기에 유지됩니다.',
  'ask.question': '질문',
  'ask.submit': '질문 제출',
  'ask.submitting': '제출 중...',
  'ask.conversations': '대화',
  'ask.no_conversations': '아직 대화가 없습니다.',
  'ask.answer': '답변',
  'ask.answer_actions': '답변 작업',
  'ask.selected_conversation': '선택한 대화',
  'ask.partial_answer': '부분 답변',
  'ask.open_evidence': '고정된 근거 열기',
  'ask.answer_status': '답변 상태',
  'ask.cancel_answer': '답변 취소',
  'ask.answer_export': '답변 내보내기 결과',
  'ask.create_or_select_project': '질문하려면 프로젝트를 만들거나 선택하세요.',
  'ask.loading_workspace': '질문 작업공간을 불러오는 중…',
  'ask.empty_landing_hint':
    '오른쪽에서 기존 대화를 선택하거나 아래 입력창에서 새 질문을 시작하세요.',
  'ask.mode': '질문 방식',
  'ask.source_context': '소스 범위',
  'ask.source_selection_unavailable': '이 질문 범위에서는 소스를 선택할 수 없습니다.',
  'ask.loading_sources': '소스를 불러오는 중…',
  'ask.sources_load_failed': '소스를 불러오지 못했습니다.',
  'ask.source_project_mismatch': '소스 라이브러리 프로젝트가 이 질문 항목과 일치하지 않습니다.',
  'ask.no_sources': '이 프로젝트에서 질문에 사용할 수 있는 소스가 없습니다.',
  'ask.pinned_version': '고정된 버전',
  'ask.version': '버전',
  'ask.check_submission_outcome': '제출 결과 확인',
  'ask.source_selection_required': '선택한 소스를 사용하려면 소스를 하나 이상 선택하세요.',
  'ask.action_required': '조치 필요:',
  'ask.review_privacy': '개인정보 검토',
  'ask.provider_eligibility_unavailable':
    '제공자 사용 가능 여부를 확인하지 못했습니다. 질문을 제출할 수 없습니다.',
  'ask.provider_eligibility.standing_policy_disabled':
    '이 프로젝트의 AI 자동 처리가 꺼져 있습니다.',
  'ask.provider_eligibility.standing_policy_provider_mismatch':
    'AI 자동 처리가 현재 구성된 제공자와 다른 제공자에 연결되어 있습니다.',
  'ask.provider_eligibility.deployment_policy_blocked':
    '현재 배포 정책에서는 이 질문에 필요한 프로젝트 내용을 구성된 AI 제공자에게 보낼 수 없습니다.',
  'ask.provider_eligibility.project_approval_required':
    '이 질문에 필요한 프로젝트 내용을 AI 제공자에게 보내려면 프로젝트 개인정보 승인이 필요합니다.',
  'ask.provider_eligibility.restricted_context_blocked':
    '제한된 프로젝트 내용은 구성된 AI 제공자에게 보낼 수 없습니다.',
  'ask.submission_unavailable': '이 대화에서는 질문을 제출할 수 없습니다.',
  'ask.current_conversation': '(현재 대화)',
  'ask.conversation_list': '대화',
  'ask.submission_rejected': '질문 제출이 거부되었습니다. 초안은 유지되었습니다.',
  'ask.submission_outcome_unknown':
    '제출 결과를 아직 확인할 수 없습니다. 기존 요청 식별자와 초안은 유지되었습니다.',
  'ask.checking_submission_outcome': '기존 제출 결과를 확인하는 중…',
  'ask.answer_result_unknown': '답변 결과를 확인할 수 없습니다. 다시 시도하기 전에 확인하세요.',
  'ask.answer_result_still_unknown':
    '답변 결과를 아직 확인할 수 없습니다. 새 요청을 보내지 말고 다시 확인하세요.',
  'ask.request_rejected': '요청이 거부되었습니다. 새 요청은 보내지 않았습니다.',
  'ask.request_pending':
    '요청이 접수되었지만 완료되지 않았습니다. 자동 재시도는 시작하지 않았습니다.',
  'ask.result_unavailable':
    '요청은 완료되었지만 결과를 아직 사용할 수 없습니다. 새 요청을 보내지 말고 다시 확인하세요.',
  'ask.answer_request_recovered': '완료된 답변 요청과 결과를 복구했습니다.',
  'ask.answer_cancel_requested': '답변 취소를 요청했습니다.',
  'ask.answer_retry_accepted': '새 시도로 답변 재시도가 접수되었습니다.',
  'ask.answer_export_completed': '답변 내보내기가 완료되었습니다.',
  'ask.transition_proposed': '초안 전환을 제안했습니다. 검증된 지식은 변경하지 않았습니다.',
  'ask.source_id': '소스 ID',
  'ask.source_version_id': '소스 버전 ID',
  'ask.failure_code': '실패 코드',
  'answer.export': '답변 내보내기',
  'answer.retry': '답변 다시 시도',
  'answer.applies_selected': '이 작업은 선택한 답변에 적용됩니다.',
  'answer.retry_same': '같은 조건으로 다시 시도',
  'answer.retry_policy': '현재 정책으로 다시 시도',
  'answer.propose_intake': '수집 초안 제안',
  'answer.propose_change': '변경 초안 제안',
  'answer.propose_directive': '지시문 제안',
  'sources.title': '소스',
  'sources.eyebrow': '지식 입력',
  'sources.create_project': '소스를 추가하기 전에 프로젝트를 만드세요',
  'sources.create_project_help': '소스를 정리하고 추가하려면 프로젝트를 만드세요.',
  'sources.draft_queue': '초안 대기열',
  'sources.draft_help': '초안은 제출하거나 버릴 때까지 생성한 프로젝트에 유지됩니다.',
  'sources.no_drafts': '아직 초안이 없습니다.',
  'sources.library': '소스 라이브러리',
  'sources.add_source': '소스 추가',
  'sources.search': '소스 검색',
  'sources.search_submit': '검색',
  'sources.loading_library': '소스 라이브러리를 불러오는 중…',
  'sources.no_matching': '일치하는 소스가 없습니다',
  'sources.none_yet': '아직 소스가 없습니다',
  'sources.change_search': '서버 검색어를 변경하거나 지우세요.',
  'sources.submitted_appear': '제출한 소스는 서버 처리 후 여기에 표시됩니다.',
  'sources.open': '소스 열기',
  'sources.unavailable': '이 소스를 사용할 수 없습니다.',
  'sources.needs_attention': '이 소스를 사용하려면 확인이 필요합니다.',
  'sources.question_access_restricted': '질문 사용 접근이 제한되었습니다.',
  'sources.questions_not_ready': '아직 질문에 사용할 수 없습니다.',
  'sources.preview_unavailable': '미리보기를 사용할 수 없습니다.',
  'sources.choose_file_again': '제출하기 전에 파일을 다시 선택하세요.',
  'sources.submission_failed': '소스 제출에 실패했습니다.',
  'sources.duplicate_decision_failed': '중복 항목 결정을 불러오지 못했습니다.',
  'sources.duplicate_resolution_failed': '중복 항목 처리를 완료하지 못했습니다.',
  'sources.cancellation_failed': '취소에 실패했습니다.',
  'sources.retry_failed': '다시 시도하지 못했습니다.',
  'sources.project_mismatch':
    '현재 프로젝트가 변경되었습니다. 이 초안은 원래 프로젝트에 격리되어 있으며 현재 범위에서는 제출할 수 없습니다.',
  'sources.invalid_draft': '이 초안을 열 수 없습니다. 내용을 확인한 후 다시 시도하세요.',
  'sources.draft_message.seeded_text_review': '제출하기 전에 생성된 직접 입력 내용을 검토하세요.',
  'sources.draft_message.seeded_text_too_large':
    '생성된 직접 입력 내용이 현재 1 MiB 한도를 초과합니다.',
  'sources.draft_message.seeded_url_validation':
    '제출할 때 서버가 URL 안전성 검증을 다시 수행합니다.',
  'sources.draft_message.seed_file_reselect':
    '파일을 다시 선택하세요. 생성된 초안은 브라우저 파일 바이트를 제공할 수 없습니다.',
  'sources.draft_message.direct_text_empty': '직접 입력 내용은 비워 둘 수 없습니다.',
  'sources.draft_message.direct_text_too_large': '직접 입력 내용이 현재 1 MiB 한도를 초과합니다.',
  'sources.draft_message.client_preflight':
    '클라이언트 사전 검사를 통과했습니다. 서버가 다시 검증합니다.',
  'sources.draft_message.file_unsupported':
    '이 섹션에서는 text/plain 및 text/markdown 형식만 사용할 수 있습니다.',
  'sources.draft_message.file_size': '파일 크기는 1바이트 이상 1 MiB 이하여야 합니다.',
  'sources.draft_message.file_preflight':
    '클라이언트 사전 검사를 통과했습니다. 서버가 바이트, 형식 및 파일 이름을 검증합니다.',
  'sources.draft_message.url_accepted':
    '로컬에서 설명자를 접수했습니다. 서버가 가져오기와 SSRF 검증을 수행합니다.',
  'sources.draft_message.url_invalid': '절대 HTTP(S) URL을 입력하세요.',
  'sources.adding_draft': '초안 추가 중…',
  'sources.submitting_drafts': '초안 제출 중…',
  'sources.input_type': '입력 유형',
  'sources.label': '이름',
  'sources.classification': '소스 분류',
  'sources.classification_help':
    '새 소스에 대한 분류 요청입니다. 서버가 최종 분류를 검증하고 저장하며 사용자의 접근 허용 수준은 변경하지 않습니다.',
  'sources.add_intake_draft': '수집 초안 추가',
  'sources.intake_drafts': '수집 초안',
  'sources.requested_classification': '요청한 분류:',
  'sources.remove': '제거',
  'sources.discard_all': '모든 초안 버리기',
  'sources.submit_drafts': '초안 제출',
  'sources.submission': '제출',
  'sources.submission_id': '제출 ID',
  'sources.submission_items': '제출 항목',
  'sources.review_duplicate': '중복 항목 검토',
  'sources.retry_same': '같은 조건으로 다시 시도',
  'sources.retry_policy': '현재 정책으로 다시 시도',
  'sources.cancel_submission': '제출 취소',
  'sources.exact_duplicate_decision': '완전 중복 항목 처리',
  'sources.existing_source': '기존 소스:',
  'sources.version': '버전',
  'sources.offline_cached':
    '오프라인입니다. 이전에 허용된 라이브러리 캐시는 표시될 수 있지만 서버 검색과 수집 작업은 차단됩니다.',
  'sources.library_stale': '이 라이브러리 정보는 오래되었습니다.',
  'sources.list': '소스',
  'source_detail.eyebrow': '소스 상세',
  'source_detail.views': '소스 상세 보기',
  'source_detail.loading': '소스를 불러오는 중…',
  'source_detail.back': '소스 라이브러리로 돌아가기',
  'source_detail.return_citation': '인용한 항목으로 돌아가기',
  'source_detail.return_knowledge': '지식 항목으로 돌아가기',
  'source_detail.version': '버전',
  'source_detail.selected': '선택됨',
  'source_detail.preview': '미리보기',
  'source_detail.questions': '질문 사용',
  'source_detail.original_preview': '원본 미리보기',
  'source_detail.loading_preview': '미리보기를 불러오는 중…',
  'source_detail.preview_unsupported':
    '원본 바이트는 사용할 수 있지만 이 미디어 형식은 인라인 미리보기를 지원하지 않습니다.',
  'source_detail.evidence': '근거',
  'source_detail.loading_evidence': '근거를 불러오는 중…',
  'source_detail.no_evidence': '아직 색인된 근거가 없습니다.',
  'source_detail.version_history': '버전 기록',
  'source_detail.loading_history': '버전 기록을 불러오는 중…',
  'source_detail.evidence_id': '근거 ID',
  'source_detail.evidence_revision': '근거 리비전',
  'source_detail.source_id': '소스 ID',
  'source_detail.source_version_id': '소스 버전 ID',
  'discovery.eyebrow': '지식 발견',
  'discovery.title': '발견 Inbox',
  'discovery.intro': '서버가 찾은 신호를 관리되는 지식 흐름에 넣기 전에 검토합니다.',
  'discovery.open_inbox': '발견 Inbox 열기',
  'discovery.back_to_knowledge': 'Knowledge Workspace로 돌아가기',
  'discovery.filter_heading': '발견 항목 필터',
  'discovery.type_filter': '발견 유형',
  'discovery.lifecycle_filter': '라이프사이클',
  'discovery.all_types': '모든 발견 유형',
  'discovery.all_lifecycles': '모든 라이프사이클 상태',
  'discovery.apply_filters': '필터 적용',
  'discovery.loading': '발견 Inbox를 불러오는 중…',
  'discovery.loading_more': '발견 항목을 더 불러오는 중…',
  'discovery.load_more': '발견 항목 더 불러오기',
  'discovery.empty_title': '발견 항목 없음',
  'discovery.empty_description': '현재 프로젝트에서 읽을 수 있는 발견 항목이 없습니다.',
  'discovery.list_failure': '발견 항목을 불러오지 못했습니다.',
  'discovery.detail_loading': '발견 항목을 불러오는 중…',
  'discovery.detail_failure': '이 발견 항목을 불러오지 못했습니다.',
  'discovery.not_found_title': '발견 항목을 사용할 수 없음',
  'discovery.not_found_description':
    '현재 프로젝트 범위에서 이 정확한 발견 리비전을 사용할 수 없습니다.',
  'discovery.non_canonical': '파생 발견 · Canonical 아님',
  'discovery.review_ready': '검토 준비됨',
  'discovery.open_review': 'Review에서 열기',
  'discovery.open_graph': '그래프에서 열기',
  'discovery.authority': '권위',
  'discovery.finding_type': '발견 유형',
  'discovery.lifecycle': '라이프사이클',
  'discovery.generation': '생성 방식',
  'discovery.summary': '요약',
  'discovery.rationale': '발견 이유',
  'discovery.derivation': '도출 방식',
  'discovery.governance': '거버넌스 상태',
  'discovery.reentry': '검증 재진입',
  'discovery.validation': '검증',
  'discovery.review_readiness': 'Review 준비 상태',
  'discovery.freshness': '최신성',
  'discovery.payload': '발견 맥락',
  'discovery.related_resources': '관련 리소스',
  'discovery.evidence': 'Evidence 및 Source 계보',
  'discovery.open_source_evidence': '소스 근거 열기',
  'discovery.open_related_resource': '관련 리소스 열기',
  'discovery.no_lineage': '이 발견 항목에 접근 가능한 계보가 없습니다.',
  'discovery.resource': '관련 지식 리소스',
  'discovery.context': '맥락',
  'discovery.subject': '대상',
  'discovery.missing_information': '누락된 정보',
  'discovery.question': '질문',
  'discovery.coverage_gap': '커버리지 공백',
  'discovery.required_evidence': '필요 근거',
  'discovery.source_endpoint': '출발점',
  'discovery.target_endpoint': '도착점',
  'discovery.proposed_relation': '제안 관계',
  'discovery.direction': '방향',
  'discovery.direction.directed': 'Directed',
  'discovery.direction.undirected': 'Undirected',
  'discovery.pattern': '패턴',
  'discovery.members': '관련 구성원',
  'discovery.contradiction': '가능한 모순',
  'discovery.investigation_next_step': '제안된 다음 단계',
  'discovery.suggested_action': '제안 작업',
  'discovery.execution_status': '실행 상태',
  'discovery.candidate_only': '후보 전용 · 실행할 수 없음',
  'discovery.risk_context': '위험 맥락',
  'discovery.no_review_action': '이 라이프사이클 상태에서는 Review를 사용할 수 없습니다.',
  'discovery.dismiss': '발견 항목 해제',
  'discovery.dismissed': '이 파생 발견 항목은 프로젝트 소유자가 해제했습니다.',
  'discovery.dismiss_failed': '발견 항목을 해제하지 못했습니다.',
  'discovery.dismiss_outcome_unknown':
    '해제 결과가 불확실합니다. 재시도하기 전에 기존 명령 결과를 확인하세요.',
  'discovery.dismiss_not_available': '이 라이프사이클 상태에서는 해제할 수 없습니다.',
  'discovery.freshness_current': '서버가 제공한 Discovery projection 기준 최신 상태입니다.',
  'discovery.freshness_revalidation': '이 발견 항목을 사용하려면 서버 재검증이 필요합니다.',
  'discovery.freshness_unknown': '서버에서 최신성을 확인할 수 없습니다.',
  'discovery.feedback.useful': '유용함',
  'discovery.feedback.not_relevant': '관련 없음',
  'discovery.feedback.heading': '피드백',
  'discovery.feedback.help':
    '이 발견 항목이 어떻게 도움이 되었는지 Shotgun에 알려주세요. 피드백은 Canonical 지식을 바꾸지 않습니다.',
  'discovery.feedback.useful_title': '유용함으로 표시',
  'discovery.feedback.not_relevant_title': '관련 없음으로 표시',
  'discovery.feedback.already_known': '이미 알고 있음',
  'discovery.feedback.too_frequent': '너무 자주 표시됨',
  'discovery.feedback.too_frequent_description': '이 발견 항목이 너무 자주 표시된다고 기록합니다.',
  'discovery.feedback.snooze': '발견 항목 잠시 보류',
  'discovery.feedback.suppress_exact': '이 발견 항목 숨기기',
  'discovery.feedback.suppress_similar': '비슷한 발견 항목 숨기기',
  'discovery.feedback.report_issue': '문제 보고',
  'discovery.feedback.history_title': '피드백 이력',
  'discovery.feedback.utility_description':
    'Canonical 지식을 바꾸지 않고 이 발견 항목이 나에게 어떻게 유용했는지 기록합니다.',
  'discovery.feedback.snooze_description':
    '이력을 삭제하거나 Canonical 지식을 바꾸지 않고 이 발견 항목을 잠시 보류합니다.',
  'discovery.feedback.snooze_finding_only': '보류는 이 발견 항목에만 적용됩니다.',
  'discovery.feedback.suppression_description':
    '선택한 범위에서 Discovery 표시를 숨깁니다. Finding을 삭제하거나 Canonical 지식을 바꾸지 않습니다.',
  'discovery.feedback.report_issue_description':
    'Shotgun에 이 발견 항목을 다시 확인하도록 요청합니다. Canonical 지식은 즉시 바뀌지 않습니다.',
  'discovery.feedback.history_description':
    '이 정확한 발견 리비전에 기록된 소유자 피드백을 확인합니다.',
  'discovery.feedback.utility_boundary':
    '표시 순서와 시점에 대한 유용성만 기록합니다. Canonical 지식은 바꾸지 않습니다.',
  'discovery.feedback.report_boundary':
    '발견 항목을 다시 확인하도록 요청합니다. Canonical 지식을 즉시 바꾸거나 Review를 승인·거절하지 않습니다.',
  'conflict_rules.title': 'Typed proposition 충돌 규칙',
  'conflict_rules.description':
    '이 규칙은 같은 정확한 쌍을 설명하는 typed relation 중 가능한 충돌로 볼 수 있는 유형을 Shotgun에 알려줍니다.',
  'conflict_rules.safety':
    '규칙만으로 relation을 거짓으로 만들거나 Fact 또는 Canonical 지식을 생성하지 않습니다.',
  'conflict_rules.list_label': '충돌 규칙',
  'conflict_rules.empty': '이 프로젝트에 설정된 충돌 규칙이 없습니다.',
  'conflict_rules.project_required': '먼저 활성 프로젝트를 선택하세요.',
  'conflict_rules.edit_title': '충돌 규칙 편집',
  'conflict_rules.add_title': '충돌 규칙 추가',
  'conflict_rules.relation_a': 'Relation 유형 A',
  'conflict_rules.relation_b': 'Relation 유형 B',
  'conflict_rules.direction': '방향 의미',
  'conflict_rules.directed': '같은 directed 관계',
  'conflict_rules.undirected': 'Undirected 관계',
  'conflict_rules.confirm_title': '충돌 규칙 변경 확인',
  'conflict_rules.confirmation':
    'Shotgun은 앞으로 일치하는 relation 쌍을 가능한 충돌로 표시합니다. 이 규칙만으로 Canonical 지식은 변경되지 않습니다.',
  'conflict_rules.check_outcome': '기존 결과 확인',
  'conflict_rules.status_active': '활성',
  'conflict_rules.status_retired': '종료됨',
  'conflict_rules.status_superseded': '대체됨',
  'discovery.feedback.scope': '적용 범위',
  'discovery.feedback.scope_finding': '이 발견 항목만',
  'discovery.feedback.scope_project': '이 프로젝트',
  'discovery.feedback.snooze_until': '보류 기간',
  'discovery.feedback.snooze_one_hour': '1시간',
  'discovery.feedback.snooze_one_day': '하루',
  'discovery.feedback.snooze_one_week': '일주일',
  'discovery.feedback.issue_kind': '무엇을 다시 확인할까요?',
  'discovery.feedback.issue.incorrect_relation': '관계가 잘못됨',
  'discovery.feedback.issue.incorrect_relation_description':
    '리소스 사이에 제안된 관계가 현재 맥락과 맞지 않습니다.',
  'discovery.feedback.issue.insufficient_evidence': '근거가 부족함',
  'discovery.feedback.issue.insufficient_evidence_description':
    '더 강하거나 완전한 뒷받침 근거가 필요합니다.',
  'discovery.feedback.issue.wrong_entity': '대상이 잘못됨',
  'discovery.feedback.issue.wrong_entity_description':
    '다른 사람·장소·사물·기록을 가리키는 것 같습니다.',
  'discovery.feedback.issue.temporal_error': '시점이 잘못됨',
  'discovery.feedback.issue.temporal_error_description':
    '사건이나 상태가 잘못된 기간에 배치된 것 같습니다.',
  'discovery.feedback.issue.misleading_pattern': '패턴이 오해를 부름',
  'discovery.feedback.issue.misleading_pattern_description':
    '보고된 패턴이 현재 정보를 잘 나타내지 못합니다.',
  'discovery.feedback.issue.misidentified_conflict': '충돌 식별이 잘못됨',
  'discovery.feedback.issue.misidentified_conflict_description':
    '실제로 존재하지 않는 충돌을 설명하는 것 같습니다.',
  'discovery.feedback.reason_optional': '선택 메모',
  'discovery.feedback.reason_count': '글자 수:',
  'discovery.feedback.submit': '피드백 기록',
  'discovery.feedback.hide_confirm': '숨기기 확인',
  'discovery.feedback.snooze_confirm': '보류 확인',
  'discovery.feedback.report_submit': '재확인 요청',
  'discovery.feedback.recorded': '피드백을 기록했습니다.',
  'discovery.feedback.recheck_requested':
    '재확인을 요청했습니다. 발견 항목이 정정되었다는 뜻은 아닙니다.',
  'discovery.feedback.failed':
    '피드백을 기록하지 못했습니다. 이 프로젝트에서 해당 발견 항목을 더 이상 사용할 수 없을 수 있습니다.',
  'discovery.feedback.outcome_unknown':
    '결과가 불확실합니다. 다시 시도하기 전에 기존 명령 결과를 확인하세요.',
  'discovery.feedback.check_result': '결과 확인',
  'discovery.feedback.history_recorded': '피드백 기록됨',
  'discovery.feedback.history_recheck_requested': '재확인 요청됨',
  'discovery.feedback.history_active': '활성',
  'discovery.feedback.history_expired': '만료됨',
  'discovery.feedback.history_until': '만료 시각',
  'discovery.feedback.history_scope': '범위',
  'discovery.feedback.history_effect': '현재 효과',
  'discovery.feedback.history_reason': '메모',
  'discovery.feedback.history_empty': '이 리비전에 기록된 소유자 피드백이 없습니다.',
  'discovery.feedback.history_loading': '피드백 이력을 불러오는 중…',
  'discovery.feedback.history_unavailable': '이 발견 항목의 피드백 이력을 사용할 수 없습니다.',
  'discovery.mandatory_visibility': '이 발견 항목에 아직 확인할 사항이 있어 표시됩니다.',
  'discovery.open_activity': '실행 활동 보기',
  'discovery.type.knowledge_gap': '지식 공백',
  'discovery.type.evidence_gap': '근거 공백',
  'discovery.type.relation_hypothesis': '관계 가설',
  'discovery.type.pattern_hypothesis': '패턴 가설',
  'discovery.type.conflict_hypothesis': '충돌 가설',
  'discovery.type.clarification_question': '명확화 질문',
  'discovery.type.action_suggestion': '작업 제안',
  'discovery.lifecycle.new': '새 항목',
  'discovery.lifecycle.validating': '검증 중',
  'discovery.lifecycle.review_ready': 'Review 준비됨',
  'discovery.lifecycle.reentered': '검증 재진입됨',
  'discovery.lifecycle.dismissed': '해제됨',
  'discovery.lifecycle.suppressed': '억제됨',
  'discovery.lifecycle.resolved': '해결됨',
  'discovery.lifecycle.stale': '오래됨',
  'discovery.lifecycle.superseded': '대체됨',
  'discovery.generation.deterministic': '규칙 기반',
  'discovery.generation.ai_assisted': 'AI 보조',
  'discovery.generation.hybrid': '규칙 및 AI 보조',
  'discovery.reentry.not_requested': '요청되지 않음',
  'discovery.reentry.processed': '처리됨',
  'discovery.reentry.ineligible': '대상 아님',
  'discovery.reentry.blocked_non_retryable': '차단됨; 재시도 불가',
  'discovery.reentry.retryable': '재시도 가능',
  'discovery.validation.not_started': '시작 전',
  'discovery.validation.validating': '검증 중',
  'discovery.validation.validated': '검증됨',
  'discovery.validation.unknown': '알 수 없음',
  'discovery.review_readiness.not_eligible': '대상 아님',
  'discovery.review_readiness.eligible': '검증 후 대상',
  'discovery.freshness.current': '최신',
  'discovery.freshness.revalidation_required': '재검증 필요',
  'discovery.freshness.unknown': '알 수 없음',
  'discovery.resource.canonical_claim': 'Canonical Claim',
  'discovery.resource.canonical_entity': 'Canonical Entity',
  'discovery.resource.canonical_event': 'Canonical Event',
  'discovery.resource.canonical_relation': 'Canonical 관계',
  'discovery.resource.canonical_conflict': 'Canonical 충돌',
  'discovery.resource.canonical_decision': 'Canonical 결정',
  'discovery.resource.source': 'Source',
  'discovery.resource.source_version': 'Source 버전',
  'discovery.resource.compiled_truth_item': 'Compiled Truth 항목',
  'enum.ask_mode.canonical_only': '검증된 지식만 사용',
  'enum.ask_mode.source_exploration': '선택한 소스 사용',
  'enum.ask_mode.hybrid': '검증된 지식과 선택한 소스 사용',
  'enum.ask_mode.unknown': '선택한 범위로 질문',
  'enum.source_preview.not_ready': '미리보기 준비 전',
  'enum.source_preview.processing': '미리보기 준비 중',
  'enum.source_preview.ready': '미리보기 준비됨',
  'enum.source_preview.failed': '미리보기 사용 불가',
  'enum.source_preview.access_restricted': '미리보기 접근 제한',
  'enum.source_preview.unknown': '미리보기 상태를 확인할 수 없음',
  'enum.source_ask.not_ready': '아직 질문에 사용할 수 없음',
  'enum.source_ask.source_version_ready': '질문에 사용 가능',
  'enum.source_ask.evidence_ready': '색인된 근거와 함께 사용 가능',
  'enum.source_ask.action_required': '사용 전 확인 필요',
  'enum.source_ask.failed': '질문에 사용할 수 없음',
  'enum.source_ask.access_restricted': '질문 사용 접근 제한',
  'enum.source_ask.unknown': '질문 사용 가능 여부를 확인할 수 없음',
  'enum.intake_state.validating': '확인 중',
  'enum.intake_state.queued': '대기 중',
  'enum.intake_state.running': '처리 중',
  'enum.intake_state.partial': '일부 완료',
  'enum.intake_state.action_required': '확인 필요',
  'enum.intake_state.succeeded': '완료',
  'enum.intake_state.failed': '실패',
  'enum.intake_state.cancel_requested': '취소 요청됨',
  'enum.intake_state.cancelled': '취소됨',
  'enum.intake_state.outcome_indeterminate': '최종 결과 확인 중',
  'enum.intake_state.unknown': '상태를 확인할 수 없음',
  'enum.intake_kind.direct_text': '직접 입력',
  'enum.intake_kind.file': '파일',
  'enum.intake_kind.url': 'URL',
  'enum.intake_kind.unknown': '소스',
  'enum.intake_validation.ready': '제출 준비됨',
  'enum.intake_validation.unsupported_format': '지원하지 않는 형식',
  'enum.intake_validation.encrypted': '암호화된 내용',
  'enum.intake_validation.corrupt': '읽을 수 없는 내용',
  'enum.intake_validation.inaccessible': '접근할 수 없음',
  'enum.intake_validation.policy_blocked': '정책에 의해 차단됨',
  'enum.intake_validation.too_large': '파일이 너무 큼',
  'enum.intake_validation.invalid_filename': '잘못된 파일 이름',
  'enum.intake_validation.invalid_url': '잘못된 URL',
  'enum.intake_validation.unsafe_destination': '안전하지 않은 대상',
  'enum.intake_validation.unknown': '확인 필요',
  'enum.duplicate.reuse': '기존 버전 사용',
  'enum.duplicate.version_candidate': '새 버전 후보 만들기',
  'enum.duplicate.separate_source': '별도 소스 만들기',
  'enum.duplicate.cancel': '이 제출 취소',
  'enum.duplicate.unknown': '중복 항목 처리',
  'enum.answer_run.queued': '대기 중',
  'enum.answer_run.running': '답변 중',
  'enum.answer_run.action_required': '확인 필요',
  'enum.answer_run.succeeded': '완료',
  'enum.answer_run.failed': '실패',
  'enum.answer_run.cancel_requested': '취소 요청됨',
  'enum.answer_run.cancelled': '취소됨',
  'enum.answer_run.outcome_unknown': '최종 결과 확인 중',
  'enum.answer_run.unknown': '답변 상태를 확인할 수 없음',
  'enum.transformation.not_started': '아직 처리되지 않음',
  'enum.transformation.running': '처리 중',
  'enum.transformation.ready': '준비됨',
  'enum.transformation.failed': '처리 실패',
  'enum.transformation.unknown': '처리 상태를 확인할 수 없음',
  'enum.evidence_origin.original': '원본 소스',
  'enum.evidence_origin.translation': '번역',
  'enum.evidence_origin.summary': '요약',
  'enum.evidence_origin.annotation': '주석',
  'enum.evidence_origin.ai_output': 'AI 결과',
  'enum.evidence_origin.unknown': '소스 근거',
  'enum.media_type.text': '텍스트',
  'enum.media_type.markdown': '마크다운',
  'enum.media_type.pdf': 'PDF',
  'enum.media_type.web': '웹 페이지',
  'enum.media_type.image': '이미지',
  'enum.media_type.document': '문서',
  'enum.sensitivity.public': '공개',
  'enum.sensitivity.internal': '내부',
  'enum.sensitivity.private': '비공개',
  'enum.sensitivity.unknown': '미분류',
};

const dictionaries: Record<ProductLocale, Record<ProductMessageKey, string>> = {
  'en-US': enUS,
  'ko-KR': koKR,
};

export type ProductTranslator = (key: ProductMessageKey) => string;

export type HfmOwnerLabelKind =
  | 'askMode'
  | 'sourcePreview'
  | 'sourceAskUsage'
  | 'intakeState'
  | 'intakeKind'
  | 'intakeValidation'
  | 'duplicateDisposition'
  | 'answerRun'
  | 'transformationState'
  | 'evidenceOrigin'
  | 'mediaType'
  | 'sensitivity';

const hfmOwnerLabelKeys: Readonly<
  Record<HfmOwnerLabelKind, Readonly<Record<string, ProductMessageKey>>>
> = {
  askMode: {
    CANONICAL_ONLY: 'enum.ask_mode.canonical_only',
    SOURCE_EXPLORATION: 'enum.ask_mode.source_exploration',
    HYBRID: 'enum.ask_mode.hybrid',
  },
  sourcePreview: {
    NOT_READY: 'enum.source_preview.not_ready',
    PROCESSING: 'enum.source_preview.processing',
    READY: 'enum.source_preview.ready',
    FAILED: 'enum.source_preview.failed',
    ACCESS_RESTRICTED: 'enum.source_preview.access_restricted',
  },
  sourceAskUsage: {
    NOT_READY: 'enum.source_ask.not_ready',
    SOURCE_VERSION_READY: 'enum.source_ask.source_version_ready',
    EVIDENCE_READY: 'enum.source_ask.evidence_ready',
    ACTION_REQUIRED: 'enum.source_ask.action_required',
    FAILED: 'enum.source_ask.failed',
    ACCESS_RESTRICTED: 'enum.source_ask.access_restricted',
  },
  intakeState: {
    VALIDATING: 'enum.intake_state.validating',
    QUEUED: 'enum.intake_state.queued',
    RUNNING: 'enum.intake_state.running',
    PARTIAL: 'enum.intake_state.partial',
    ACTION_REQUIRED: 'enum.intake_state.action_required',
    SUCCEEDED: 'enum.intake_state.succeeded',
    FAILED: 'enum.intake_state.failed',
    CANCEL_REQUESTED: 'enum.intake_state.cancel_requested',
    CANCELLED: 'enum.intake_state.cancelled',
    OUTCOME_INDETERMINATE: 'enum.intake_state.outcome_indeterminate',
  },
  intakeKind: {
    DIRECT_TEXT: 'enum.intake_kind.direct_text',
    FILE: 'enum.intake_kind.file',
    FILE_METADATA: 'enum.intake_kind.file',
    URL: 'enum.intake_kind.url',
  },
  intakeValidation: {
    READY: 'enum.intake_validation.ready',
    VALID: 'enum.intake_validation.ready',
    UNSUPPORTED_FORMAT: 'enum.intake_validation.unsupported_format',
    ENCRYPTED: 'enum.intake_validation.encrypted',
    CORRUPT: 'enum.intake_validation.corrupt',
    INACCESSIBLE: 'enum.intake_validation.inaccessible',
    POLICY_BLOCKED: 'enum.intake_validation.policy_blocked',
    TOO_LARGE: 'enum.intake_validation.too_large',
    INVALID_FILENAME: 'enum.intake_validation.invalid_filename',
    INVALID_URL: 'enum.intake_validation.invalid_url',
    UNSAFE_DESTINATION: 'enum.intake_validation.unsafe_destination',
  },
  duplicateDisposition: {
    REUSE_EXISTING_VERSION: 'enum.duplicate.reuse',
    CREATE_VERSION_CANDIDATE: 'enum.duplicate.version_candidate',
    CREATE_SEPARATE_SOURCE: 'enum.duplicate.separate_source',
    CANCEL_SUBMISSION: 'enum.duplicate.cancel',
  },
  answerRun: {
    QUEUED: 'enum.answer_run.queued',
    RUNNING: 'enum.answer_run.running',
    STREAMING: 'enum.answer_run.running',
    ACTION_REQUIRED: 'enum.answer_run.action_required',
    SUCCEEDED: 'enum.answer_run.succeeded',
    FAILED: 'enum.answer_run.failed',
    CANCEL_REQUESTED: 'enum.answer_run.cancel_requested',
    CANCELLED: 'enum.answer_run.cancelled',
    OUTCOME_UNKNOWN: 'enum.answer_run.outcome_unknown',
  },
  transformationState: {
    NOT_STARTED: 'enum.transformation.not_started',
    RUNNING: 'enum.transformation.running',
    READY: 'enum.transformation.ready',
    FAILED: 'enum.transformation.failed',
  },
  evidenceOrigin: {
    ORIGINAL: 'enum.evidence_origin.original',
    TRANSLATION: 'enum.evidence_origin.translation',
    SUMMARY: 'enum.evidence_origin.summary',
    ANNOTATION: 'enum.evidence_origin.annotation',
    AI_OUTPUT: 'enum.evidence_origin.ai_output',
  },
  mediaType: {
    'text/plain': 'enum.media_type.text',
    'text/markdown': 'enum.media_type.markdown',
    'application/pdf': 'enum.media_type.pdf',
    'text/html': 'enum.media_type.web',
  },
  sensitivity: {
    public: 'enum.sensitivity.public',
    internal: 'enum.sensitivity.internal',
    private: 'enum.sensitivity.private',
  },
};

const hfmOwnerFallbackKeys: Readonly<Record<HfmOwnerLabelKind, ProductMessageKey>> = {
  askMode: 'enum.ask_mode.unknown',
  sourcePreview: 'enum.source_preview.unknown',
  sourceAskUsage: 'enum.source_ask.unknown',
  intakeState: 'enum.intake_state.unknown',
  intakeKind: 'enum.intake_kind.unknown',
  intakeValidation: 'enum.intake_validation.unknown',
  duplicateDisposition: 'enum.duplicate.unknown',
  answerRun: 'enum.answer_run.unknown',
  transformationState: 'enum.transformation.unknown',
  evidenceOrigin: 'enum.evidence_origin.unknown',
  mediaType: 'enum.media_type.document',
  sensitivity: 'enum.sensitivity.unknown',
};

export const hfmOwnerLabel = (
  t: ProductTranslator,
  kind: HfmOwnerLabelKind,
  value: string,
): string => {
  const key = hfmOwnerLabelKeys[kind][value];
  if (key) return t(key);
  if (kind === 'mediaType' && value.startsWith('image/')) return t('enum.media_type.image');
  return t(hfmOwnerFallbackKeys[kind]);
};

export const resolveProductLocale = (value: unknown): ProductLocale =>
  value === 'ko-KR' || value === 'en-US' ? value : 'en-US';

type ProductLocalizationValue = {
  readonly locale: ProductLocale;
  readonly t: ProductTranslator;
};

const defaultLocalization: ProductLocalizationValue = {
  locale: 'en-US',
  t: (key) => enUS[key],
};

const ProductLocalizationContext = createContext<ProductLocalizationValue>(defaultLocalization);

export const ProductLocalizationProvider = ({
  children,
  principalId,
}: {
  readonly children: ReactNode;
  readonly principalId: string;
}) => {
  const { apiClient } = useAppRuntime();
  const preferences = useQuery({
    queryKey: principalPreferencesQueryKey(principalId),
    queryFn: () => apiClient.getPrincipalPreferences(),
    staleTime: Number.POSITIVE_INFINITY,
  });
  const locale = resolveProductLocale(preferences.data?.preferences['locale']);
  const value = useMemo<ProductLocalizationValue>(
    () => ({ locale, t: (key) => dictionaries[locale][key] }),
    [locale],
  );

  if (preferences.isPending) {
    return <p role="status">{enUS['common.loading_preferences']}</p>;
  }

  return (
    <ProductLocalizationContext.Provider value={value}>
      {children}
    </ProductLocalizationContext.Provider>
  );
};

export const useProductLocalization = (): ProductLocalizationValue =>
  useContext(ProductLocalizationContext);
